// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Time-as-state helpers. The Multiplayer Server sleeps when the scene empties
// and cold-starts on the next visit, so running timers die: persist absolute
// deadlines (or a change-point snapshot) and derive "remaining" from the
// clock, on both sides, every frame.

export function remainingMs(endsAtMs: number, nowMs: number): number {
  return Math.max(0, endsAtMs - nowMs)
}

export function isExpired(endsAtMs: number, nowMs: number): boolean {
  return nowMs >= endsAtMs
}

// Drift-free countdown that survives speed changes: store the state at the
// last change and derive from the clock. remaining = remainingAtChange −
// (now − changedAt) × multiplier, clamped at zero.
export interface CountdownState {
  changedAtMs: number
  remainingAtChangeMs: number
  multiplier: number
}

export function countdownRemainingMs(state: CountdownState, nowMs: number): number {
  const elapsed = Math.max(0, nowMs - state.changedAtMs)
  return Math.max(0, state.remainingAtChangeMs - elapsed * state.multiplier)
}

export function countdownWithMultiplier(state: CountdownState, nowMs: number, multiplier: number): CountdownState {
  return {
    changedAtMs: nowMs,
    remainingAtChangeMs: countdownRemainingMs(state, nowMs),
    multiplier
  }
}

// Settle anything that expired while the server slept: call from server init,
// after restoring persisted state and before systems run.
export function settleExpired<T>(
  items: readonly T[],
  endsAtOf: (item: T) => number,
  nowMs: number,
  settle: (item: T) => void
): number {
  let settled = 0
  for (const item of items) {
    if (isExpired(endsAtOf(item), nowMs)) {
      settle(item)
      settled++
    }
  }
  return settled
}

// Epoch-derived period ids: "reset weekly" is the key rolling over, not a cron
// job — the sleeping server cannot run one.
export function periodId(nowMs: number, periodMs: number, epochMs = 0): number {
  return Math.floor((nowMs - epochMs) / periodMs)
}

export const DAY_MS = 24 * 60 * 60 * 1000
export const WEEK_MS = 7 * DAY_MS

export function dailyKey(prefix: string, nowMs: number): string {
  return `${prefix}:daily:${periodId(nowMs, DAY_MS)}`
}

export function weeklyKey(prefix: string, nowMs: number): string {
  return `${prefix}:weekly:${periodId(nowMs, WEEK_MS)}`
}
