// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// The pure heart of the `game` module: message dispatch, per-name FIFO, rate
// limits, payload hygiene, the publish and broadcast budgets, presence and zone
// verification.
// No SDK imports — the SDK-facing half (game.ts) wires these ports to the real
// transport; the harness wires them to a simulated world. Everything testable
// lives here.
//
// Two verbs, one meaning each. A client calls request() and the server answers
// it in onRequest(); the server calls broadcast() and every client hears it in
// onBroadcast(). Nothing here infers which way a name flows: the verb says it.

import { rotateVec, type Quat, type Vec3 } from './worldTransform'
import { zoneKey } from './zoneRegistry'

export type { Quat, Vec3 }

export type Player = string

export type ErrorSide = 'server' | 'you'

export interface ErrorCard {
  side: ErrorSide
  name: string
  message: string
}

export interface CorePorts {
  now(): number
  /** The official isServer(), read fresh on every call. The role is never
   * cached: the platform resolves it one system after start(), so a value
   * pushed in at fork time is false for every start() on the real server. */
  isServerNow(): boolean
  /** client → server: correlated request, resolves with the handler's JSON answer */
  sendRequest(name: string, json: string): Promise<string>
  /** server → clients: a one-way broadcast, to everyone or to one player */
  sendBroadcast(name: string, json: string, to?: Player): void
  /** server only: publish one shared fact (SDK half: a protectSynced SharedFact
   * entity per key; harness: the world's fact store). Reliable, snapshotted —
   * late joiners receive every fact without any message. */
  publishFact(key: string, json: string, rev: number): void
  /** server only, boot: retire a stale fact that survived the last run's
   * snapshot. SDK half: remove the entity (defer-a-tick rule applies there). */
  retireFact(key: string, rev: number): void
  /** surface an error card ([server] / [you]) — never silent */
  emitError(card: ErrorCard): void
  /** dev-Play warning (size budgets etc.) — never an error, never silent */
  devWarn(message: string): void
  /** boot: the saved record that survived sleep (serverState-backed in the
   * SDK half; the harness: a store that outlives restarts, unlike facts) */
  loadSaved(): Promise<Record<string, unknown>>
  /** server write-behind: hand one saved key to the persistence layer — it
   * checkpoints (round end, player leave), never per tick */
  storeSaved(key: string, value: unknown): void
  /** boot/join: one player's durable record ({} on a first visit) */
  loadPlayerData(player: Player): Promise<Record<string, unknown>>
  /** server write-behind: the player's whole record, checkpointed like saved */
  storePlayerData(player: Player, data: Record<string, unknown>): void
  /** leave checkpoint: write this player's pending record now — the debounce
   * window would outlive their visit */
  flushPlayerData(player: Player): void
  /** leave checkpoint: drop the transport's per-player memory (the replay cache
   * for their request ids), so a full room costs no more than the room */
  dropPlayer(player: Player): void
  /** server: every volume carrying this zone key — [] when no such zone is placed */
  findZones(zoneKey: string): ZoneVolume[]
  /** server: a player's feet in scene coords, null until comms delivers their avatar */
  playerPosition(player: Player): Vec3 | null
  /** server: the seed committed for the round being started. Drawn ahead into
   * server-private state (serverState in the SDK half — never synced, throws on
   * a client) and replaced with a fresh draw on every take, so no client can
   * precompute a layout before its round starts (§11 seed secrecy). */
  takeNextSeed(): number
}

// §11 hardening defaults. Tunable per handler later; the caps are checked
// before dispatch so malformed or oversized input never reaches creator code.
const RATE_PER_S = 8
export const MAX_PAYLOAD_BYTES = 4096
// The call-site cap, checked BEFORE anything is sent. The transport drops a
// message over ~13 KB without a word, so an oversize send would otherwise
// vanish, burn its retries and reject as a timeout with nothing to pull on.
export const MAX_SEND_BYTES = 12_000
// Per-key state size guard: one SharedFact must stay far from the transport's
// 12 KB chunk edge. Warn, don't block — the creator may be mid-refactor.
const FACT_WARN_BYTES = 4096
// Per-key publish budget. setState is legal from a plain server update(), which
// is ~41 writes per key per second with nothing else in this path to stop them.
// Over budget the key stays dirty and publishes its NEWEST value once a token
// refills — coalescing, never dropping, so the last write always ships.
export const PUBLISH_PER_KEY_PER_S = 8
// §11.2: one player must not bloat the isolate or the Storage budget.
export const PLAYER_DATA_CAP_BYTES = 8192
// Zone verification (ported from zone-authority): positions arrive at ≤10 Hz
// and are the avatar's FEET while the real collider is a 2 m capsule, so an
// honest player standing on the boundary must not be called a cheat.
const ZONE_SLACK_M = 1
// A member whose position the server cannot see at all (still loading, comms
// hiccup) keeps their place this long before the sweep gives up on them.
const ZONE_LOST_GRACE_MS = 10_000
// Zone claims are edge-triggered by the client's own zone bus, so an honest
// player sends a couple per zone per visit; the sweep re-checks at 4 Hz anyway.
const ZONE_CLAIMS_PER_S = 4
// The pre-boot queues are fed by every client and drained only when boot ends,
// and the per-player rate limit lives PAST the gate — so unbounded they grow
// for as long as waking takes. The cap is generous next to a cold start (a
// client holds its own requests while the ladder says waking); over it the
// NEWEST is refused, which keeps the asks a player is actually waiting on.
export const MAX_PREBOOT_REQUESTS = 256
// One queue, two ends: the client parks a request while the ladder says waking,
// the server parks it until boot ends. Both are capped at MAX_PREBOOT_REQUESTS,
// and both answer a flood from here — a creator who reads either console is told
// the same thing, whichever end refused the ask.
export const WAKING_FLOOD_NAME = 'game.request:waking'
export const WAKING_FLOOD = `Over ${MAX_PREBOOT_REQUESTS} requests arrived while the server was waking, so the newest ones were dropped — call game.request once per player action, not every frame.`
export function wakingDropped(name: string): string {
  return `'${name}' was dropped while the server was waking — ask for it again once the server is running.`
}

export interface ZoneVolume {
  shape: 'box' | 'sphere'
  center: Vec3
  rotation: Quat
  scale: Vec3
}

// Same volume definition the engine uses (ADR-258): a UNIT box or sphere scaled
// by the entity's world transform; `slack` widens every half-extent by metres.
// The point moves into the volume's own frame (inverse rotation about the
// centre); scale stays in the half-extents, which keeps non-uniform scale exact.
function insideZone(volume: ZoneVolume, point: Vec3, slack: number): boolean {
  const { center, rotation, scale } = volume
  if (scale.x <= 0 || scale.y <= 0 || scale.z <= 0) return false
  const margin = slack > 0 ? slack : 0
  const half = { x: scale.x / 2 + margin, y: scale.y / 2 + margin, z: scale.z / 2 + margin }
  const inverse = { x: -rotation.x, y: -rotation.y, z: -rotation.z, w: rotation.w }
  const local = rotateVec(inverse, { x: point.x - center.x, y: point.y - center.y, z: point.z - center.z })
  if (volume.shape === 'sphere') {
    const x = local.x / half.x
    const y = local.y / half.y
    const z = local.z / half.z
    return x * x + y * y + z * z <= 1
  }
  return Math.abs(local.x) <= half.x && Math.abs(local.y) <= half.y && Math.abs(local.z) <= half.z
}

// The round tuple (§2.2): the numbers every client reconstructs a round from,
// plus the id real games key per-round validity on (§12 #2). It rides
// game.state under one reserved key, so a late joiner gets the current round
// from the snapshot like any other fact — no second mechanism.
//
// The number counts rounds inside ONE wake of the Multiplayer Server: state
// resets when the server sleeps (§5 lifetimes), so the count starts again at 1
// — which is why the id, and not the number, is what survives being written
// down. Same shape as the number for a reader ('k3f9x2-7'), and never twice.
const ROUND_STATE_KEY = 'round'

export interface RoundInfo {
  /** This round, once ever — `<wake>-<number>`. Compare it with ===, write it
   * down, print it. Two rounds never share one, not even across a sleep. */
  id: string
  /** 1, 2, 3… within this wake of the Multiplayer Server. The server sleeps
   * when the scene is empty and counts from 1 again when it wakes, so anything
   * kept past the round it belongs to — in game.saved, in game.playerData —
   * has to hold the id instead. */
  number: number
  seed: number
  phase: number
  phaseStartMs: number
  configVersion: number
}

function zeroRound(): RoundInfo {
  return { id: '', number: 0, seed: 0, phase: 0, phaseStartMs: 0, configVersion: 0 }
}

/** Defensive read: the tuple crossed the wire, and a creator can clobber the
 * reserved key — a corrupt field must not poison every derived layout. */
function asRoundInfo(value: unknown): RoundInfo {
  if (typeof value !== 'object' || value === null) return zeroRound()
  const record = value as Record<string, unknown>
  const read = (key: Exclude<keyof RoundInfo, 'id'>): number => {
    const raw = record[key]
    return typeof raw === 'number' && Number.isFinite(raw) ? Math.floor(raw) : 0
  }
  const number = read('number')
  const id = record.id
  // No id is no round: everything that keys on one would otherwise key on the
  // empty string and call two different rounds the same round.
  if (number <= 0 || typeof id !== 'string' || id === '') return zeroRound()
  return {
    id,
    number,
    seed: read('seed'),
    phase: read('phase'),
    phaseStartMs: read('phaseStartMs'),
    configVersion: read('configVersion')
  }
}

/** The tag every round id this wake carries: the instant the Multiplayer
 * Server woke, salted with the first seed it drew — so a wake cannot reuse the
 * one before it, and neither can the round numbers counted inside it. */
function wakeTag(nowMs: number, seed: number): string {
  return ((Math.imul(nowMs | 0, 0x9e3779b1) ^ seed) >>> 0).toString(36)
}

/** One rng stream per (round seed, prefab): two layouts sharing a round must
 * not share draws (the draw-order contract, rng.ts rule 1). */
export function layoutSeed(seed: number, prefab: string): number {
  let h = seed | 0
  for (let i = 0; i < prefab.length; i++) h = (Math.imul(h, 31) + prefab.charCodeAt(i)) | 0
  return h
}

// The Game Config version pinned into the tuple, published by the generated
// src/scripts/game-config.ts on globalThis — the only channel a carried module
// copy can read it through (the round-loop precedent).
function configVersionNow(): number {
  const bag = (globalThis as unknown as Record<string, unknown>).__dclGameConfig_v1
  const version = typeof bag === 'object' && bag !== null ? (bag as Record<string, unknown>).version : undefined
  return typeof version === 'number' && Number.isFinite(version) && version >= 0 ? Math.floor(version) : 0
}

// Every guard string is a rule plus the exact next gesture, and the gesture is
// one that exists today. They are REPORTED, never thrown: a throw in start()
// aborts the whole scene's construction, and a throw in update() is caught and
// re-printed at ~41 Hz forever.
const SET_STATE_GUARD = 'game.setState only runs on the server. Put this line inside if (isServer()).'
const ROUND_KEY_GUARD = 'game.state.round is the round itself. Use game.newRound(), or pick another name for your key.'
const SAVED_GUARD = 'game.saved only runs on the server. Put this line inside if (isServer()).'
const SAVED_WAKE_GUARD = 'game.saved is loaded when the server wakes. Read it inside game.onReady, not in start().'
const SAVED_UNREADABLE_GUARD =
  'game.saved could not be read when the server woke, so it is off for this run — check the Multiplayer Server is running, then play again.'
const PLAYER_DATA_GUARD = 'game.playerData only runs on the server. Put this line inside if (isServer()).'
const PLAYER_DATA_WAKE_GUARD =
  'game.playerData is loaded when the server wakes. Read it inside game.onReady, not in start().'
const POSITION_GUARD = 'game.positionOf only runs on the server. Put this line inside if (isServer()).'
const NEW_ROUND_GUARD = 'game.newRound only runs on the server. Put this line inside if (isServer()).'
const REQUEST_GUARD = 'game.request only runs on the client. Move this line out of if (isServer()).'
const BROADCAST_GUARD = 'game.broadcast only runs on the server. Put this line inside if (isServer()).'
const ON_REQUEST_GUARD = 'game.onRequest only runs on the server. Put this line inside if (isServer()).'
const ON_BROADCAST_GUARD = 'game.onBroadcast only runs on the client. Move this line out of if (isServer()).'
const ON_READY_GUARD = 'game.onReady only runs on the server. Put this line inside if (isServer()).'
const ON_PLAYER_JOIN_GUARD = 'game.onPlayerJoin only runs on the server. Put this line inside if (isServer()).'
const ON_PLAYER_LEAVE_GUARD = 'game.onPlayerLeave only runs on the server. Put this line inside if (isServer()).'
const ON_ENTER_AREA_GUARD = 'game.onEnterArea only runs on the server. Put this line inside if (isServer()).'
const ON_ROUND_START_GUARD = 'game.onRoundStart only runs on the server. Put this line inside if (isServer()).'

// Best effort, and only paid when a card is actually reported (once per verb
// per session): the frame that broke the rule, as "Class.method, file.ts". A
// bundle that flattens names degrades to the method, or to nothing at all.
export function callerLabel(): string {
  for (const line of (new Error().stack ?? '').split('\n').slice(2)) {
    const file = /([^/\\ ('")]+\.[tj]sx?)/.exec(line)
    if (file === null || file[1] === 'game.ts' || file[1] === 'gameCore.ts') continue
    const fn = /at\s+(?:new\s+)?([\w$]+(?:\.[\w$]+)*)\s*\(/.exec(line)
    const where = fn === null || fn[1].startsWith('Object') ? '' : `${fn[1]}, `
    return `${where}${file[1]}`
  }
  return ''
}

function tooMuchData(name: string, cap: number = MAX_SEND_BYTES): string {
  return `'${name}' carries too much data — send less than ${cap} bytes.`
}

function why(e: unknown): string {
  return e instanceof Error ? e.message : String(e)
}

// A broadcast's budget and its held payload are per recipient. Sharing one key
// across recipients would let one player's message overwrite another's.
function broadcastKey(name: string, to?: Player): string {
  return to === undefined ? `broadcast:${name}` : `broadcast:${name}\u0000${to}`
}

type RequestHandler = (data: unknown, player: Player) => unknown | Promise<unknown>
type BroadcastHandler = (data: unknown) => void

interface HandlerEntry {
  fn: RequestHandler
  scriptId: string
}

export class GameNameError extends Error {
  constructor(name: string) {
    super(`No handler named '${name}'. Answer it with game.onRequest('${name}', …) on the server.`)
    this.name = 'GameNameError'
  }
}

interface Bucket {
  tokens: number
  atMs: number
}

export class RateLimiter {
  private buckets = new Map<string, Bucket>()
  constructor(private ratePerS: number = RATE_PER_S) {}

  allow(name: string, player: Player, nowMs: number): boolean {
    const key = `${name}\0${player}`
    const b = this.buckets.get(key) ?? { tokens: this.ratePerS, atMs: nowMs }
    b.tokens = Math.min(this.ratePerS, b.tokens + ((nowMs - b.atMs) / 1000) * this.ratePerS)
    b.atMs = nowMs
    if (b.tokens < 1) {
      this.buckets.set(key, b)
      return false
    }
    b.tokens -= 1
    this.buckets.set(key, b)
    return true
  }
}

type StateListener = (changed: Record<string, unknown>) => void
type PresenceFn = (player: Player) => void | Promise<void>
export type ZoneClaimKind = 'enter' | 'exit'
export interface ZoneClaimReply {
  ok: boolean
  verified: boolean
}

/** A write for a player whose record is not in memory: what has been queued
 * since their load started, and the composed record once it resolved. */
interface PendingPlayerWrite {
  patch: Record<string, unknown>
  record: Record<string, unknown> | null
}

export class GameCore {
  // Two registries, because there are two contracts: a request is answered on
  // the server, a broadcast is heard on the client. One name can be both.
  // A request has one answer, so one name has one handler; a broadcast is a
  // moment, and every listener on that name hears it.
  private requestHandlers = new Map<string, HandlerEntry>()
  private broadcastHandlers = new Map<string, BroadcastHandler[]>()
  private queues = new Map<string, Promise<void>>()
  private limiter = new RateLimiter()
  private zoneLimiter = new RateLimiter(ZONE_CLAIMS_PER_S)
  private publishLimiter = new RateLimiter(PUBLISH_PER_KEY_PER_S)
  /** broadcasts over budget: name → its newest payload, shipped on a refill */
  // Keyed by name AND recipient: one player's respawn must never coalesce onto
  // another's. Everyone-broadcasts share a key; a per-player one gets its own.
  private heldBroadcasts = new Map<string, { name: string; json: string; to?: Player }>()
  // One card per guard per session: a guard reachable from update() would
  // otherwise print at frame rate for the rest of the play.
  private reported = new Set<string>()

  // Shared facts: the state mirror every side reads; only the server writes.
  // Each top-level key becomes its own published fact (per-key sharding keeps
  // any single write far from the chunk edge and lets unrelated keys move
  // independently). Writes coalesce: at most one publish per key per tick.
  readonly state: Record<string, unknown> = {}
  private revs = new Map<string, number>()
  private dirty = new Map<string, unknown>()
  private stateListeners: StateListener[] = []
  private hasBooted = false
  // True once the boot restore has run: saved and the present players' records
  // are in memory. onReady runs inside this window, start() runs before it.
  private memoryLoaded = false
  private savedData: Record<string, unknown> = {}
  // True when boot could not read saved data. The server still runs, but
  // game.saved stays shut: an empty in-memory copy that accepted writes would
  // be flushed over the record the creator actually has stored.
  private savedUnreadable = false
  private playerRecords = new Map<Player, Record<string, unknown>>()
  private playerLoads = new Map<Player, Promise<void>>()
  /** writes for players whose record is not in memory, keyed by wallet */
  private pendingPatches = new Map<Player, PendingPlayerWrite>()
  private onReadyFns: Array<() => void | Promise<void>> = []
  private roundStartFns: Array<(round: RoundInfo) => void | Promise<void>> = []
  /** this isolate's wake tag, drawn with the first round it starts */
  private wake = ''
  private preBootRequests: Array<{
    name: string
    json: string
    from: Player
    resolve: (json: string) => void
    reject: (e: Error) => void
  }> = []
  // Presence: the wallets the server currently sees, diffed every tick against
  // the synced identity roster the SDK half enumerates.
  private present = new Set<Player>()
  private joinFns: PresenceFn[] = []
  private leaveFns: PresenceFn[] = []
  // Zones: zone key → verified members. The value is the ms at which the sweep
  // lost sight of that member's position, 0 while it can see them.
  private zoneMembers = new Map<string, Map<Player, number>>()
  private zoneEnterFns = new Map<string, PresenceFn[]>()
  private preBootZoneClaims: Array<{
    zone: string
    kind: ZoneClaimKind
    player: Player
    resolve: (reply: ZoneClaimReply) => void
    reject: (e: Error) => void
  }> = []

  constructor(private ports: CorePorts) {}

  private onServer(): boolean {
    return this.ports.isServerNow()
  }

  /** One card per key per session, on the side that broke the rule, naming the
   * method it was called from so the creator does not have to search. */
  private report(key: string, message: string): void {
    if (this.reported.has(key)) return
    this.reported.add(key)
    const at = callerLabel()
    this.ports.emitError({
      side: this.onServer() ? 'server' : 'you',
      name: at === '' ? key : `${key} in ${at}`,
      message
    })
  }

  /** True when this call is on the side the verb belongs to; otherwise it has
   * already reported and the caller must return without doing anything. */
  private onRightSide(verb: string, wantServer: boolean, rule: string): boolean {
    if (this.onServer() === wantServer) return true
    this.report(verb, rule)
    return false
  }

  /**
   * game.onRequest(name, fn): the server's answer to something a player asks.
   * One handler per name — re-registering from the same script replaces (a
   * prefab placed twice shares one handler); a different script claiming the
   * name reports and keeps the first.
   */
  onRequest(name: string, fn: RequestHandler, scriptId: string): void {
    if (!this.onRightSide('game.onRequest', true, ON_REQUEST_GUARD)) return
    const existing = this.requestHandlers.get(name)
    if (existing !== undefined && existing.scriptId !== scriptId) {
      this.report(
        `game.onRequest:${name}`,
        `Two scripts both handle '${name}' (${existing.scriptId} and ${scriptId}). One name has one answer — rename one of them.`
      )
      return
    }
    this.requestHandlers.set(name, { fn, scriptId })
  }

  /**
   * game.onBroadcast(name, fn): what a client hears from the server. Every
   * listener on the name hears it — two prefabs reacting to one moment is the
   * normal case, and neither owns the name. Returns the detach function a
   * released clone calls, the way zoneBus.onZone does.
   */
  onBroadcast(name: string, fn: BroadcastHandler): () => void {
    if (!this.onRightSide('game.onBroadcast', false, ON_BROADCAST_GUARD)) return () => {}
    const listeners = this.broadcastHandlers.get(name) ?? []
    listeners.push(fn)
    this.broadcastHandlers.set(name, listeners)
    return () => {
      const current = this.broadcastHandlers.get(name)
      if (current === undefined) return
      const at = current.indexOf(fn)
      if (at < 0) return
      current.splice(at, 1)
      if (current.length === 0) this.broadcastHandlers.delete(name)
    }
  }

  /** game.request — a client asks the server and awaits its answer. */
  async request(name: string, data: unknown): Promise<unknown> {
    if (!this.onRightSide('game.request', false, REQUEST_GUARD)) return undefined
    const json = JSON.stringify(data ?? {})
    // the server refuses at MAX_PAYLOAD_BYTES, so name that number here or a
    // creator trims to the one they were given and is refused a second time
    if (json.length > MAX_PAYLOAD_BYTES) throw new Error(tooMuchData(name, MAX_PAYLOAD_BYTES))
    const reply = await this.ports.sendRequest(name, json)
    return reply === '' ? null : JSON.parse(reply)
  }

  /**
   * game.broadcast — the server tells every client, or one player with `to`.
   * Budgeted per name like a state key: a name over budget holds its NEWEST
   * payload and ships it the moment a token refills, so a broadcast written in
   * a server update() costs the room 8 messages a second, not 41.
   */
  broadcast(name: string, data: unknown, to?: Player): void {
    if (!this.onRightSide('game.broadcast', true, BROADCAST_GUARD)) return
    const json = JSON.stringify(data ?? {})
    if (json.length > MAX_SEND_BYTES) {
      this.report(`game.broadcast:${name}`, tooMuchData(name))
      return
    }
    // A name with a payload already waiting keeps waiting: sending this one
    // straight out the moment a token refilled would deliver it BEFORE the
    // older one the flush still holds.
    const held = broadcastKey(name, to)
    if (this.heldBroadcasts.has(held)) {
      this.heldBroadcasts.set(held, { name, json, to })
      return
    }
    if (!this.publishLimiter.allow(held, 'server', this.ports.now())) {
      this.heldBroadcasts.set(held, { name, json, to })
      this.report(
        `broadcast.${name}`,
        `'${name}' is sent more than ${PUBLISH_PER_KEY_PER_S} times a second, so the server is sending only the newest one. Send it on a timer with game.every, or send it once when it starts and once when it stops.`
      )
      return
    }
    this.ports.sendBroadcast(name, json, to)
  }

  /** Server tick: ship the newest held payload for every name back in budget. */
  private flushBroadcasts(): void {
    if (this.heldBroadcasts.size === 0) return
    const nowMs = this.ports.now()
    for (const [key, held] of [...this.heldBroadcasts]) {
      if (!this.publishLimiter.allow(key, 'server', nowMs)) continue
      this.heldBroadcasts.delete(key)
      this.ports.sendBroadcast(held.name, held.json, held.to)
    }
  }

  /**
   * Server dispatch of an incoming request: hygiene first (rate, size), then
   * the per-name FIFO — awaited, crash-contained. The answer is the
   * handler's return, JSON-encoded; hygiene rejections and unknown names
   * reject so the asking client's await fails loudly, never silently.
   */
  handleRequest(name: string, json: string, from: Player): Promise<string> {
    if (!this.hasBooted) {
      // waking: requests queue instead of failing — drained at the end of boot
      if (this.preBootRequests.length >= MAX_PREBOOT_REQUESTS) {
        this.report(WAKING_FLOOD_NAME, WAKING_FLOOD)
        return Promise.reject(new Error(wakingDropped(name)))
      }
      return new Promise<string>((resolve, reject) => {
        this.preBootRequests.push({ name, json, from, resolve, reject })
      })
    }
    const entry = this.requestHandlers.get(name)
    if (!entry) return Promise.reject(new GameNameError(name))
    if (!this.limiter.allow(name, from, this.ports.now())) {
      // One card per (name, player) per session: honest traffic that trips the
      // cap would otherwise be the loudest thing in the Play console.
      const key = `dropped:${name}\0${from}`
      if (!this.reported.has(key)) {
        this.reported.add(key)
        this.ports.emitError({ side: 'server', name, message: `'${name}' from ${from} dropped — too many per second.` })
      }
      return Promise.reject(new Error(`'${name}' dropped — asked too often. Send it less often.`))
    }
    if (json.length > MAX_PAYLOAD_BYTES) {
      return Promise.reject(new Error(tooMuchData(name, MAX_PAYLOAD_BYTES)))
    }
    let data: unknown
    try {
      data = json === '' ? undefined : JSON.parse(json)
    } catch {
      return Promise.reject(new Error(`'${name}' payload is not valid JSON.`))
    }
    // The chain orders one name's handlers; it must never carry a failure
    // forward, or one rejected request would stop every later one on that name.
    const prev = (this.queues.get(name) ?? Promise.resolve()).catch(() => {})
    let result: unknown
    let failed: Error | null = null
    const run = prev.then(async () => {
      try {
        result = await entry.fn(data, from)
      } catch (e) {
        failed = e instanceof Error ? e : new Error(String(e))
        this.ports.emitError({ side: 'server', name, message: `${entry.scriptId}: ${failed.message}` })
      } finally {
        this.flushState()
      }
    })
    this.queues.set(name, run)
    return run.then(() => {
      if (failed) throw failed
      return JSON.stringify(result ?? null)
    })
  }

  /** game.setState — the server's write to the shared mirror. Values land in
   * the mirror at once (a handler reads its own writes) and publish on flush. */
  setState(patch: Record<string, unknown>): void {
    if (!this.onRightSide('game.setState', true, SET_STATE_GUARD)) return
    for (const [key, value] of Object.entries(patch)) {
      if (key === ROUND_STATE_KEY) {
        this.report('game.state.round', ROUND_KEY_GUARD)
        continue
      }
      this.state[key] = value
      this.dirty.set(key, value)
    }
  }

  onStateChange(listener: StateListener): void {
    this.stateListeners.push(listener)
  }

  /** Server: publish dirty keys — at most one write per key per flush, and at
   * most PUBLISH_PER_KEY_PER_S per key per second. A key over its budget stays
   * dirty and ships its newest value as soon as a token refills. */
  flushState(): void {
    if (!this.onServer()) return
    this.flushBroadcasts()
    if (this.dirty.size === 0) return
    const nowMs = this.ports.now()
    const deferred = new Map<string, unknown>()
    try {
      for (const [key, value] of this.dirty) {
        if (!this.publishLimiter.allow(`state:${key}`, 'server', nowMs)) {
          deferred.set(key, value)
          this.report(
            `state.${key}`,
            `game.state.${key} changes more than ${PUBLISH_PER_KEY_PER_S} times a second, so the server is sending only the newest value. Change it on a timer with game.every, not every frame.`
          )
          continue
        }
        let json: string
        try {
          json = JSON.stringify(value ?? null)
        } catch {
          // a value JSON can't carry (a BigInt, a cycle) must cost one key, not
          // the frame: publishing runs from an engine system and a finally block
          this.state[key] = undefined
          this.ports.emitError({
            side: 'server',
            name: `state.${key}`,
            message: `game.state.${key} can't be shared — use plain numbers, strings, booleans, arrays and objects.`
          })
          continue
        }
        if (json.length > FACT_WARN_BYTES) {
          this.ports.devWarn(`game.state.${key} is over ${FACT_WARN_BYTES} bytes — split it into smaller keys.`)
        }
        const rev = (this.revs.get(key) ?? 0) + 1
        this.revs.set(key, rev)
        try {
          this.ports.publishFact(key, json, rev)
        } catch (e) {
          this.ports.emitError({
            side: 'server',
            name: `state.${key}`,
            message: `game.state.${key} could not be shared this time: ${e instanceof Error ? e.message : String(e)}`
          })
        }
      }
    } finally {
      this.dirty.clear()
      for (const [key, value] of deferred) this.dirty.set(key, value)
    }
  }

  /** Client: one shared fact arrived (live change or snapshot). Stale revs —
   * a re-delivered snapshot behind the live stream — are dropped. */
  applyFact(key: string, json: string, rev: number): void {
    const known = this.revs.get(key) ?? 0
    if (rev <= known) return
    this.revs.set(key, rev)
    let value: unknown
    try {
      value = JSON.parse(json)
    } catch {
      this.ports.emitError({ side: 'you', name: `state.${key}`, message: 'synced state arrived with invalid JSON.' })
      return
    }
    this.state[key] = value
    const changed = { [key]: value }
    for (const listener of this.stateListeners) {
      try {
        listener(changed)
      } catch (e) {
        this.ports.emitError({ side: 'you', name: `state.${key}`, message: e instanceof Error ? e.message : String(e) })
      }
    }
  }

  /** Client: a fact was retired (boot wipe). The key leaves the mirror. */
  applyRetire(key: string, rev: number): void {
    const known = this.revs.get(key) ?? 0
    if (rev <= known) return
    this.revs.set(key, rev)
    if (!(key in this.state)) return
    delete this.state[key]
    const changed = { [key]: undefined }
    for (const listener of this.stateListeners) {
      try {
        listener(changed)
      } catch (e) {
        this.ports.emitError({ side: 'you', name: `state.${key}`, message: e instanceof Error ? e.message : String(e) })
      }
    }
  }

  /** game.saved — survives restarts and re-publishes, unlike game.state.
   * Server only, reading and writing; change values through set (a reference
   * mutated in place never reaches the persistence layer). */
  readonly saved = {
    get: (key: string): unknown => {
      if (!this.savedReady('game.saved.get')) return undefined
      return this.savedData[key]
    },
    set: (key: string, value: unknown): void => {
      if (!this.savedReady('game.saved.set')) return
      this.savedData[key] = value
      this.ports.storeSaved(key, value)
    }
  }

  private savedReady(verb: string): boolean {
    if (!this.onRightSide(verb, true, SAVED_GUARD)) return false
    if (this.savedUnreadable) {
      this.report(`${verb}:unreadable`, SAVED_UNREADABLE_GUARD)
      return false
    }
    if (this.memoryLoaded) return true
    this.report(`${verb}:waking`, SAVED_WAKE_GUARD)
    return false
  }

  /** game.playerData(player) — the per-wallet durable record. Server only;
   * set patches top-level keys (the setState shape), capped per player. */
  playerData(player: Player): {
    get(): Record<string, unknown>
    set(patch: Record<string, unknown>): void
  } {
    return {
      get: () => {
        if (!this.playerDataReady('game.playerData.get')) return {}
        return this.playerRecord(player)
      },
      set: (patch) => {
        if (!this.playerDataReady('game.playerData.set')) return
        // Writing on top of a record we have not loaded would turn a patch
        // into a replace and wipe everything that player earned before today.
        // A round-end tally naming someone who just logged off is ordinary,
        // so the patch waits for their record to load and lands on top of it.
        const loaded = this.playerRecords.get(player)
        if (!loaded) {
          this.queuePlayerPatch(player, patch)
          return
        }
        const next = this.writePlayerData(player, loaded, patch)
        if (next !== null) this.playerRecords.set(player, next)
      }
    }
  }

  private playerDataReady(verb: string): boolean {
    if (!this.onRightSide(verb, true, PLAYER_DATA_GUARD)) return false
    if (this.memoryLoaded) return true
    this.report(`${verb}:waking`, PLAYER_DATA_WAKE_GUARD)
    return false
  }

  // A player who left has no record in memory — reading theirs at round end is
  // ordinary (they logged off mid-round), so it reads as a first visit does
  // rather than aborting the caller's remaining work.
  private playerRecord(player: Player): Record<string, unknown> {
    return this.playerRecords.get(player) ?? {}
  }

  /** Compose a patch onto a record and hand the result to storage. A record
   * over the cap moves nowhere — not memory, not storage — so the next patch
   * still composes on what actually holds. */
  private writePlayerData(
    player: Player,
    base: Record<string, unknown>,
    patch: Record<string, unknown>
  ): Record<string, unknown> | null {
    const next = { ...base, ...patch }
    const bytes = JSON.stringify(next).length
    if (bytes > PLAYER_DATA_CAP_BYTES) {
      this.report(
        'game.playerData:cap',
        `One player's data would be ${bytes} bytes and the cap is ${PLAYER_DATA_CAP_BYTES}, so this change was not saved. Store fewer keys per player.`
      )
      return null
    }
    this.ports.storePlayerData(player, next)
    return next
  }

  /**
   * A write for a player whose record is not in memory: hold the patch, load
   * what they have ONCE, and compose every later patch on that result. Storage
   * is write-behind, so re-reading it per write would answer with the record as
   * it was BEFORE the queued write — the second award would replace the first
   * and the first would be gone at the flush. The composed copy therefore stays
   * in memory until the record is restored, which adopts it (adoptQueuedWrites)
   * and is what stops it growing on a departed player's behalf.
   */
  private queuePlayerPatch(player: Player, patch: Record<string, unknown>): void {
    const pending = this.pendingPatches.get(player)
    if (pending !== undefined) {
      // Still loading: its handler composes and stores whatever is queued here
      // by the time it lands. Loaded: this patch is the only thing left to
      // carry the composed record to storage.
      if (pending.record === null) {
        Object.assign(pending.patch, patch)
        return
      }
      const next = this.writePlayerData(player, pending.record, patch)
      if (next !== null) pending.record = next
      return
    }
    const entry: PendingPlayerWrite = { patch: { ...patch }, record: null }
    this.pendingPatches.set(player, entry)
    void this.ports
      .loadPlayerData(player)
      .then((stored) => {
        // a restore adopted this write across the await — its copy is the newer
        // one, so this answer is stale and must not be written back over it
        if (this.pendingPatches.get(player) !== entry) return
        // patches queued while the read was in flight outrank what it returned
        entry.record = this.writePlayerData(player, stored, entry.patch) ?? { ...stored }
        entry.patch = {}
      })
      .catch((e: unknown) => {
        this.pendingPatches.delete(player)
        this.ports.emitError({
          side: 'server',
          name: 'playerData',
          message: `couldn't save data for a player who left: ${e instanceof Error ? e.message : String(e)}`
        })
      })
  }

  // Writes queued while the record was out of memory sit in the write-behind
  // buffer, so the record storage just handed back can be behind them: they
  // compose on top and go out again, and the restore is what takes ownership.
  private adoptQueuedWrites(player: Player, stored: Record<string, unknown>): Record<string, unknown> {
    const pending = this.pendingPatches.get(player)
    if (pending === undefined) return stored
    this.pendingPatches.delete(player)
    const queued = { ...(pending.record ?? {}), ...pending.patch }
    return this.writePlayerData(player, stored, queued) ?? pending.record ?? stored
  }

  /** Awaited by the SDK half before a player's first server handler (and by
   * bootServer for players already present), so .get() never races the load. */
  async restorePlayerData(player: Player): Promise<void> {
    if (this.playerRecords.has(player)) return
    // N requests in one tick must cost one storage read, not N: the host-call
    // budget is scene-wide, and blowing it makes every player's writes fail
    const inFlight = this.playerLoads.get(player)
    if (inFlight) return inFlight
    const load = this.ports
      .loadPlayerData(player)
      .then((data) => {
        // a server set may have landed across the await — never clobber it
        if (!this.playerRecords.has(player)) this.playerRecords.set(player, this.adoptQueuedWrites(player, data))
      })
      .finally(() => this.playerLoads.delete(player))
    this.playerLoads.set(player, load)
    return load
  }

  /** game.onReady — the server's boot hook: runs once when the server wakes up
   * (not per player, not per round), after restart cleanup. It is the only hook
   * that runs AFTER saved data has loaded, which is why game.saved read in
   * start() finds nothing. */
  onReady(fn: () => void | Promise<void>): void {
    if (!this.onRightSide('game.onReady', true, ON_READY_GUARD)) return
    this.onReadyFns.push(fn)
  }

  booted(): boolean {
    return this.hasBooted
  }

  /**
   * The server boot pipeline, in the honest order: re-adopt the facts that
   * survived the last run's snapshot (seeding revs so every fresh publish
   * OUTRUNS the stale copy a connected client still holds) → retire them —
   * state resets when the server sleeps → restore durable memory (saved, plus
   * playerData for the players already present) so onReady can copy saved
   * back in for continuity → run the onReady hooks → flush → open for
   * requests and drain anything that queued while waking.
   *
   * Storage is the one step that fails on its own: a refused read is reported
   * and the ladder keeps going, because a server with no saved data is a
   * server that can still answer (saved data starts empty on a first run).
   * Anything else that fails REJECTS — the caller withholds the heartbeat, so
   * the life ladder never says running for a server that never finished waking
   * — but the gate opens either way: a closed gate parks every client's request
   * until the transport times it out and answers nothing at all.
   */
  async bootServer(
    adopted: Array<{ key: string; json: string; rev: number }>,
    players: Player[] = []
  ): Promise<void> {
    if (this.hasBooted) return
    try {
      for (const fact of adopted) {
        const rev = fact.rev + 1
        this.revs.set(fact.key, rev)
        this.ports.retireFact(fact.key, rev)
      }
      // Storage first, and its faults stop here: a refused read costs that
      // record, never the ladder below it.
      try {
        this.savedData = await this.ports.loadSaved()
      } catch (e) {
        this.savedUnreadable = true
        this.savedData = {}
        this.ports.emitError({
          side: 'server',
          name: 'game.saved',
          message: `Saved data could not be read (${why(e)}), so game.saved is off for this run — check the Multiplayer Server is running, then play again.`
        })
      }
      await Promise.all(
        players.map((p) =>
          this.restorePlayerData(p).catch((e: unknown) => {
            this.report(
              'game.playerData:unreadable',
              `A player's saved data could not be read (${why(e)}), so the server sees them as a first visit — check the Multiplayer Server is running, then play again.`
            )
          })
        )
      )
      this.memoryLoaded = true
      await this.runOnServer('onReady', this.onReadyFns)
      // Round 1 starts at boot (unless an onReady hook already called newRound):
      // layouts exist from the first frame, and the round-1 reset runs like any
      // other round's. The counter resets with the state, per the §5 lifetimes —
      // this wake's round 1 is a different round from the last wake's, and only
      // the id says so.
      if (this.round.number === 0) {
        await this.runOnServer('onRoundStart', this.roundStartFns, this.beginRound(1))
      }
    } catch (e) {
      this.ports.emitError({
        side: 'server',
        name: 'game',
        message: `The server didn't finish waking (${why(e)}), so some of this run's setup never ran — check the Multiplayer Server is running, then play again.`
      })
      throw e
    } finally {
      this.openForRequests()
    }
  }

  /** The gate every request waits behind, opened once — and drained, so
   * nothing that queued while waking is left unanswered. */
  private openForRequests(): void {
    if (this.hasBooted) return
    this.hasBooted = true
    const queued = this.preBootRequests
    this.preBootRequests = []
    for (const q of queued) {
      // handleRequest rejects synchronously on a bad name: one queued request
      // must never abort the drain and leave the rest of the queue unanswered
      try {
        this.handleRequest(q.name, q.json, q.from).then(q.resolve, q.reject)
      } catch (e) {
        q.reject(e instanceof Error ? e : new Error(String(e)))
      }
    }
    const claims = this.preBootZoneClaims
    this.preBootZoneClaims = []
    for (const c of claims) {
      this.zoneClaim(c.zone, c.kind, c.player).then(c.resolve, c.reject)
    }
  }

  // One span, shared by every callback family: errors surface as a card on the
  // side that ran the callback and never wedge the caller; dirty state flushes
  // on the way out.
  private async runOnServer<A extends unknown[]>(
    name: string,
    fns: ReadonlyArray<(...args: A) => unknown>,
    ...args: A
  ): Promise<void> {
    try {
      for (const fn of fns) {
        try {
          await fn(...args)
        } catch (e) {
          this.ports.emitError({
            side: this.onServer() ? 'server' : 'you',
            name,
            message: e instanceof Error ? e.message : String(e)
          })
        }
      }
    } finally {
      this.flushState()
    }
  }

  /** game.onPlayerJoin — runs on the server when a player arrives. */
  onPlayerJoin(fn: PresenceFn): void {
    if (!this.onRightSide('game.onPlayerJoin', true, ON_PLAYER_JOIN_GUARD)) return
    this.joinFns.push(fn)
  }

  /** game.onPlayerLeave — runs on the server when a player leaves. */
  onPlayerLeave(fn: PresenceFn): void {
    if (!this.onRightSide('game.onPlayerLeave', true, ON_PLAYER_LEAVE_GUARD)) return
    this.leaveFns.push(fn)
  }

  /**
   * Server tick input: every wallet the engine can currently see. The diff
   * against the last roster IS join/leave — SDK onEnterScene never fires on
   * the server, so the synced identity set is the only truth.
   */
  presentPlayers(present: Player[]): void {
    if (!this.onServer() || !this.hasBooted) return
    const now = new Set(present)
    for (const player of now) {
      if (this.present.has(player)) continue
      this.present.add(player)
      void this.playerJoined(player)
    }
    for (const player of [...this.present]) {
      if (now.has(player)) continue
      this.present.delete(player)
      void this.playerLeft(player)
    }
  }

  private async playerJoined(player: Player): Promise<void> {
    await this.restorePlayerData(player)
    await this.runOnServer('onPlayerJoin', this.joinFns, player)
  }

  private async playerLeft(player: Player): Promise<void> {
    for (const key of [...this.zoneMembers.keys()]) this.dropZoneMember(key, player)
    if (this.leaveFns.length > 0) {
      await this.restorePlayerData(player)
      await this.runOnServer('onPlayerLeave', this.leaveFns, player)
      // A leave handler is the only thing that makes this method yield, and a
      // player can rejoin while it does — a comms flap, a fast reconnect. By
      // then presentPlayers has run playerJoined and their record is loaded
      // again, so the eviction below would be reading a departure that is over:
      // .get() would answer {} for a player who is standing in the scene, and
      // dropPlayer would forget the replies their in-flight retries dedupe
      // against, re-running handlers SEEN_PER_CALLER exists to run once.
      if (this.present.has(player)) return
    }
    this.ports.flushPlayerData(player)
    this.ports.dropPlayer(player)
    this.playerRecords.delete(player)
  }

  /** game.onEnterArea — runs on the server once the player's entry is verified.
   * The client watches every placed Trigger Area through its own zone bus, so
   * the side this is registered on is the server's, like every other hook. */
  onEnterArea(zone: string, fn: PresenceFn): void {
    if (!this.onRightSide('game.onEnterArea', true, ON_ENTER_AREA_GUARD)) return
    const key = zoneKey(zone)
    this.zoneEnterFns.set(key, [...(this.zoneEnterFns.get(key) ?? []), fn])
  }

  /**
   * Server: a client claims its player crossed a named zone. Never trusted —
   * an enter is re-verified against the server's own position view (slack,
   * because positions are ≤10 Hz feet), with grace for an avatar comms has not
   * delivered yet; an exit is always honored (the sweep would drop them
   * anyway). Pre-boot claims queue like requests.
   */
  zoneClaim(zone: string, kind: ZoneClaimKind, player: Player): Promise<ZoneClaimReply> {
    if (!this.hasBooted) {
      // Same unbounded-queue problem as requests, and a refusal is already the
      // ordinary answer here (the client's zone bus re-claims on the next
      // crossing), so an over-full queue needs no card of its own.
      if (this.preBootZoneClaims.length >= MAX_PREBOOT_REQUESTS) {
        return Promise.resolve({ ok: false, verified: false })
      }
      return new Promise<ZoneClaimReply>((resolve, reject) => {
        this.preBootZoneClaims.push({ zone, kind, player, resolve, reject })
      })
    }
    // Claims arrive off the wire like any request: a client alternating
    // enter/exit at transport rate would otherwise run creator code — and a
    // full position scan — as fast as it can send. The cap matches the sweep's
    // own rate. The name arrives off the wire too, so check it against the
    // zones this scene actually listens to BEFORE anything is allocated for it:
    // otherwise a client invents a fresh name per claim and every one costs a
    // full scan and a permanent bucket. Every placed area is watched now, so a
    // refused claim for an area nobody listens to is ordinary, not an attack.
    const key = zoneKey(zone)
    if (!this.zoneEnterFns.has(key)) {
      return Promise.resolve({ ok: false, verified: false })
    }
    if (!this.zoneLimiter.allow(`zone:${key}`, player, this.ports.now())) {
      return Promise.resolve({ ok: false, verified: false })
    }
    try {
      return Promise.resolve(this.settleZoneClaim(zone, kind, player))
    } catch (e) {
      return Promise.reject(e instanceof Error ? e : new Error(String(e)))
    }
  }

  private settleZoneClaim(zone: string, kind: ZoneClaimKind, player: Player): ZoneClaimReply {
    const key = zoneKey(zone)
    if (key === '') throw new Error('a zone claim needs a zone name')
    if (kind === 'exit') {
      this.dropZoneMember(key, player)
      return { ok: true, verified: true }
    }
    const volumes = this.ports.findZones(key)
    if (volumes.length === 0) throw new Error(`no zone named "${zone.trim()}"`)
    const position = this.ports.playerPosition(player)
    if (position === null) {
      // Late-joiner grace: rejecting every arriving player's first entry would
      // be worse than admitting one unverified — the sweep drops them the
      // moment their position arrives outside.
      this.admitZoneMember(key, player)
      return { ok: true, verified: false }
    }
    if (!volumes.some((v) => insideZone(v, position, ZONE_SLACK_M))) {
      this.dropZoneMember(key, player)
      throw new Error(`outside "${zone.trim()}"`)
    }
    this.admitZoneMember(key, player)
    return { ok: true, verified: true }
  }

  private admitZoneMember(key: string, player: Player): void {
    const members = this.zoneMembers.get(key) ?? new Map<Player, number>()
    this.zoneMembers.set(key, members)
    // The lost-sight clock starts at admission and never restarts: re-claiming
    // must not buy a player another grace window the server can't verify.
    if (members.has(player)) return
    members.set(player, 0)
    const fns = this.zoneEnterFns.get(key)
    if (!fns || fns.length === 0) return
    // A zone enter may be this player's first handler on the server.
    void this.restorePlayerData(player).then(() => this.runOnServer('onEnterArea', fns, player))
  }

  private dropZoneMember(key: string, player: Player): void {
    const members = this.zoneMembers.get(key)
    if (!members?.has(player)) return
    members.delete(player)
    if (members.size === 0) this.zoneMembers.delete(key)
  }

  /** Server, ~4 Hz: re-check every verified member against the position view. */
  sweepZones(nowMs: number): void {
    if (!this.onServer() || !this.hasBooted) return
    for (const [key, members] of [...this.zoneMembers]) {
      const volumes = this.ports.findZones(key)
      for (const [player, lostSinceMs] of [...members]) {
        if (volumes.length === 0) {
          this.dropZoneMember(key, player)
          continue
        }
        const position = this.ports.playerPosition(player)
        if (position === null) {
          if (lostSinceMs === 0) members.set(player, nowMs)
          else if (nowMs - lostSinceMs > ZONE_LOST_GRACE_MS) this.dropZoneMember(key, player)
          continue
        }
        if (volumes.some((v) => insideZone(v, position, ZONE_SLACK_M))) members.set(player, 0)
        else this.dropZoneMember(key, player)
      }
    }
  }

  /** game.positionOf — feet, ~10×/second; server only. */
  positionOf(player: Player): Vec3 | null {
    if (!this.onRightSide('game.positionOf', true, POSITION_GUARD)) return null
    return this.ports.playerPosition(player)
  }

  /** game.every's tick, on whichever side it was written — errors card, never
   * wedge the interval. */
  runEvery(fn: () => void | Promise<void>): Promise<void> {
    return this.runOnServer('every', [fn])
  }

  /** game.round — read anywhere; id is '' and number is 0 until the first
   * round lands. */
  get round(): RoundInfo {
    return asRoundInfo(this.state[ROUND_STATE_KEY])
  }

  /** game.onRoundStart — server only (§12 #1): clients react through onStateChange. */
  onRoundStart(fn: (round: RoundInfo) => void | Promise<void>): void {
    if (!this.onRightSide('game.onRoundStart', true, ON_ROUND_START_GUARD)) return
    this.roundStartFns.push(fn)
  }

  /** game.newRound — server only: stamps the next id, bumps the number,
   * publishes the seed drawn for this round, and runs the onRoundStart hooks. */
  newRound(): RoundInfo {
    if (!this.onRightSide('game.newRound', true, NEW_ROUND_GUARD)) return this.round
    const tuple = this.beginRound(this.round.number + 1)
    // deferred a microtask: the caller's own work finishes first
    void Promise.resolve().then(() => this.runOnServer('onRoundStart', this.roundStartFns, tuple))
    return tuple
  }

  // The tuple rides the facts path like any state key — written directly so
  // boot can start round 1 through the same door a handler uses.
  private beginRound(number: number): RoundInfo {
    const nowMs = this.ports.now()
    const seed = this.ports.takeNextSeed()
    if (this.wake === '') this.wake = wakeTag(nowMs, seed)
    const tuple: RoundInfo = {
      id: `${this.wake}-${number}`,
      number,
      seed,
      phase: 0,
      phaseStartMs: nowMs,
      configVersion: configVersionNow()
    }
    this.state[ROUND_STATE_KEY] = tuple
    this.dirty.set(ROUND_STATE_KEY, tuple)
    return tuple
  }

  /** Client dispatch of an incoming broadcast: every listener on the name, in
   * registration order, each contained so one that throws does not cost the
   * others their moment. Unmatched names are dropped quietly — a client may
   * legitimately not care — but malformed ones surface. */
  handleBroadcast(name: string, json: string): void {
    const listeners = this.broadcastHandlers.get(name)
    if (listeners === undefined || listeners.length === 0) return
    let data: unknown
    try {
      data = json === '' ? undefined : JSON.parse(json)
    } catch {
      this.ports.emitError({ side: 'you', name, message: `'${name}' arrived with invalid JSON.` })
      return
    }
    for (const fn of [...listeners]) {
      try {
        fn(data)
      } catch (e) {
        this.ports.emitError({ side: 'you', name, message: e instanceof Error ? e.message : String(e) })
      }
    }
  }
}
