// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Server-liveness ladder. A heartbeat VALUE in synced state is not proof of
// life — a stale CRDT snapshot from a previous server run carries one. Life is
// "the value changed recently, by MY clock": track the client-observed time of
// the last change, never the heartbeat's own timestamp (immune to snapshots
// and clock skew).

export type ServerLifeState = 'connecting' | 'alive' | 'lost'

export class LivenessTracker {
  private lastValue: number | null = null
  private observedAtMs: number | null = null

  constructor(private staleAfterMs: number) {}

  /** Feed the currently visible heartbeat value (or null when absent). */
  observe(value: number | null, nowMs: number): void {
    if (value === null || value === this.lastValue) return
    this.lastValue = value
    this.observedAtMs = nowMs
  }

  state(nowMs: number): ServerLifeState {
    if (this.observedAtMs === null) return 'connecting'
    return nowMs - this.observedAtMs <= this.staleAfterMs ? 'alive' : 'lost'
  }

  /** True exactly once: the first observed change. */
  everAlive(): boolean {
    return this.observedAtMs !== null
  }
}
