// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Normalize-on-read for persisted state: whatever comes back from Storage is
// untrusted (older schema versions, partial writes, hand-edits in the live
// storage UI) — repair it into the current shape instead of crashing on it.

export function safeNumber(v: unknown, fallback: number): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : fallback
}

export function safeString(v: unknown, fallback: string): string {
  return typeof v === 'string' ? v : fallback
}

export function safeBoolean(v: unknown, fallback: boolean): boolean {
  return typeof v === 'boolean' ? v : fallback
}

export function safeStringArray(v: unknown): string[] {
  return Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : []
}

export interface Versioned {
  schemaVersion: number
}

/**
 * Version gate + repair in one place. `raw` from an unknown/older schema falls
 * back to `defaults()`; a current-version value is still passed through
 * `repair` so every field is individually validated.
 */
export function normalizeVersioned<T extends Versioned>(
  raw: unknown,
  schemaVersion: number,
  defaults: () => T,
  repair: (value: Partial<T>, defaults: T) => T
): T {
  const maybe = raw as Partial<T> | null
  if (!maybe || typeof maybe !== 'object' || maybe.schemaVersion !== schemaVersion) return defaults()
  return repair(maybe, defaults())
}
