// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// The outcome ledger: the sequenced, server-owned record of what happened to
// pooled instances (`hit`, `died`, …).
//
// Planned-mode clones are client-local, so gameplay results cannot be read off
// the entities — every client has a different zombie #17. The ledger is the one
// shared truth: the server appends, the sequence numbers make delivery gaps
// detectable, and a client that missed chunk 4 asks for it over rpc instead of
// silently diverging (one lost broadcast used to mean a permanently wrong
// alive-set on one client).
//
// What this deliberately does NOT do: decide anything. Validation, clamps and
// cooldowns live in the server's validators — this only orders and delivers.

export interface OutcomeEntry {
  seq: number
  instanceId: number
  kind: string
  value: number
}

/** Retained history; older entries are unrepairable and clients fast-forward instead. */
const MAX_RETAINED = 2048

/** Out-of-order entries held while waiting for the gap to be repaired. */
const MAX_BUFFERED = 512

/** Server side: assigns sequence numbers and answers repair requests. */
export class OutcomeLog {
  private log: OutcomeEntry[] = []
  private seq = 0

  get lastSeq(): number {
    return this.seq
  }

  /** The oldest seq still answerable; 0 when nothing has been trimmed. */
  get firstSeq(): number {
    return this.log.length === 0 ? this.seq + 1 : this.log[0].seq
  }

  append(instanceId: number, kind: string, value: number): OutcomeEntry {
    this.seq += 1
    const entry: OutcomeEntry = { seq: this.seq, instanceId, kind, value }
    this.log.push(entry)
    if (this.log.length > MAX_RETAINED) this.log.splice(0, this.log.length - MAX_RETAINED)
    return entry
  }

  /** Everything after `seq`, oldest first. */
  since(seq: number): OutcomeEntry[] {
    return this.log.filter((entry) => entry.seq > seq)
  }

  entries(): OutcomeEntry[] {
    return [...this.log]
  }

  /** Restore from durable state after a server restart; the sequence continues from it. */
  restore(entries: OutcomeEntry[]): void {
    this.log = sortEntries(entries).slice(-MAX_RETAINED)
    this.seq = this.log.length === 0 ? 0 : this.log[this.log.length - 1].seq
  }
}

/** Client side: applies entries strictly in seq order and reports the gaps it cannot fill. */
export class OutcomeStream {
  private seen = 0
  private buffer = new Map<number, OutcomeEntry>()

  get lastSeq(): number {
    return this.seen
  }

  get bufferedCount(): number {
    return this.buffer.size
  }

  /**
   * Accept a delivery. Returns the entries that became applicable, in order, plus
   * the seq to ask the server for when something is still missing in front of the
   * buffered tail.
   */
  accept(entries: OutcomeEntry[]): { applied: OutcomeEntry[]; gapFrom: number | null } {
    for (const entry of sortEntries(entries)) {
      if (entry.seq <= this.seen) continue
      this.buffer.set(entry.seq, entry)
    }
    const applied: OutcomeEntry[] = []
    for (;;) {
      const next = this.buffer.get(this.seen + 1)
      if (next === undefined) break
      this.buffer.delete(next.seq)
      this.seen = next.seq
      applied.push(next)
    }
    this.trimBuffer()
    return { applied, gapFrom: this.buffer.size === 0 ? null : this.seen + 1 }
  }

  /**
   * Jump the stream to a delivered history — the rejoin path, and the answer when
   * the missing entries have already been trimmed server-side.
   */
  fastForward(entries: OutcomeEntry[]): OutcomeEntry[] {
    const ordered = sortEntries(entries)
    this.buffer.clear()
    if (ordered.length === 0) return []
    this.seen = ordered[ordered.length - 1].seq
    return ordered
  }

  reset(): void {
    this.seen = 0
    this.buffer.clear()
  }

  private trimBuffer(): void {
    if (this.buffer.size <= MAX_BUFFERED) return
    const drop = [...this.buffer.keys()].sort((a, b) => b - a).slice(0, this.buffer.size - MAX_BUFFERED)
    for (const seq of drop) this.buffer.delete(seq)
  }
}

/** Split a delivery so no single message approaches the transport's ~13 KB ceiling. */
export function chunkEntries(entries: OutcomeEntry[], size: number): OutcomeEntry[][] {
  if (size < 1) return entries.length === 0 ? [] : [entries]
  const chunks: OutcomeEntry[][] = []
  for (let i = 0; i < entries.length; i += size) chunks.push(entries.slice(i, i + size))
  return chunks
}

/** Decode one entry off the wire; anything malformed is dropped rather than trusted. */
export function readOutcomeEntry(value: unknown): OutcomeEntry | null {
  if (typeof value !== 'object' || value === null) return null
  const record = value as Record<string, unknown>
  const { seq, instanceId, kind, value: amount } = record
  if (typeof seq !== 'number' || !Number.isFinite(seq) || seq < 1) return null
  if (typeof instanceId !== 'number' || !Number.isFinite(instanceId)) return null
  if (typeof kind !== 'string' || kind === '') return null
  return { seq, instanceId, kind, value: typeof amount === 'number' && Number.isFinite(amount) ? amount : 0 }
}

export function readOutcomeEntries(value: unknown): OutcomeEntry[] {
  if (!Array.isArray(value)) return []
  const entries: OutcomeEntry[] = []
  for (const item of value) {
    const entry = readOutcomeEntry(item)
    if (entry !== null) entries.push(entry)
  }
  return entries
}

function sortEntries(entries: OutcomeEntry[]): OutcomeEntry[] {
  return [...entries].sort((a, b) => a.seq - b.seq)
}
