// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Request/response correlation for RPC over fire-and-forget messages: pending
// calls keyed by id, resolved by the matching response, retried on a timer,
// failed after the retry budget. Clock is injected — fully unit-testable.

export interface PendingEntry<T> {
  resolve: (value: T) => void
  reject: (error: Error) => void
  sentAtMs: number
  retriesLeft: number
}

export class PendingMap<T> {
  private entries = new Map<string, PendingEntry<T>>()

  add(id: string, entry: PendingEntry<T>): void {
    this.entries.set(id, entry)
  }

  settle(id: string, value: T): boolean {
    const entry = this.entries.get(id)
    if (!entry) return false
    this.entries.delete(id)
    entry.resolve(value)
    return true
  }

  fail(id: string, error: Error): boolean {
    const entry = this.entries.get(id)
    if (!entry) return false
    this.entries.delete(id)
    entry.reject(error)
    return true
  }

  /**
   * Advance timeouts: entries older than timeoutMs either consume a retry
   * (returned so the caller resends, with sentAtMs reset) or fail.
   */
  tick(nowMs: number, timeoutMs: number): string[] {
    const resend: string[] = []
    for (const [id, entry] of [...this.entries]) {
      if (nowMs - entry.sentAtMs < timeoutMs) continue
      if (entry.retriesLeft > 0) {
        entry.retriesLeft--
        entry.sentAtMs = nowMs
        resend.push(id)
      } else {
        this.entries.delete(id)
        entry.reject(new Error(`rpc timeout: ${id}`))
      }
    }
    return resend
  }

  get size(): number {
    return this.entries.size
  }
}
