// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Phase machine as DEADLINE-AS-STATE. A round loop is not a running timer: the
// Multiplayer Server sleeps when the scene empties and cold-starts on the next
// visit, so the only durable form of "which phase are we in" is the tuple
// {phase, phaseStartMs} plus a table of phase durations. Everything else —
// current phase, remaining time, how many boundaries were missed while the
// server was down — is DERIVED from the clock, identically on server and
// client, every frame.
//
// The duration table is a CYCLE: phase 0 uses durationsMs[0], phase 1 uses
// durationsMs[1], … and phase N wraps to durationsMs[N % length]. `phase` keeps
// counting up forever so it doubles as the round number and as an rng seed
// component.
//
// A non-positive duration never expires: it parks the machine on that phase
// until something writes a new tuple (the "wait for players" lobby).

export interface PhaseTuple {
  phase: number
  phaseStartMs: number
}

/** Boundaries crossed since the last observation. */
export interface PhaseAdvance {
  /** Phases entered, in order. Always at least one entry. */
  entered: number[]
  /** Phases dropped because the gap exceeded the catch-up budget. */
  skipped: number
}

// A slept server can wake days later. The cycle fast-path handles that in O(1);
// this bound only guards the leftover partial cycle and tables containing a
// non-positive duration.
const MAX_CATCH_UP_STEPS = 1024

export function phaseIndexOf(phase: number, count: number): number {
  if (count <= 0) return 0
  const trunc = Math.trunc(phase)
  return ((trunc % count) + count) % count
}

export function cycleMsOf(durationsMs: readonly number[]): number {
  let total = 0
  for (const duration of durationsMs) total += duration
  return total
}

export function durationOf(tuple: PhaseTuple, durationsMs: readonly number[]): number {
  if (durationsMs.length === 0) return 0
  return durationsMs[phaseIndexOf(tuple.phase, durationsMs.length)]
}

/**
 * Walk the tuple forward to whatever phase `nowMs` lands in. Pure, allocation-
 * light, and safe to call every frame on both sides — the server persists the
 * RESULT at each boundary, the client only derives it.
 */
export function advancePhase(tuple: PhaseTuple, durationsMs: readonly number[], nowMs: number): PhaseTuple {
  const count = durationsMs.length
  let phase = Math.trunc(tuple.phase)
  let phaseStartMs = tuple.phaseStartMs
  if (count === 0 || !(nowMs > phaseStartMs)) return { phase, phaseStartMs }

  // Whole cycles in one step, so a week of downtime costs the same as a second.
  if (durationsMs.every((duration) => duration > 0)) {
    const cycleMs = cycleMsOf(durationsMs)
    const cycles = Math.floor((nowMs - phaseStartMs) / cycleMs)
    if (cycles > 0) {
      phase += cycles * count
      phaseStartMs += cycles * cycleMs
    }
  }

  for (let step = 0; step < MAX_CATCH_UP_STEPS; step++) {
    const duration = durationsMs[phaseIndexOf(phase, count)]
    if (duration <= 0 || nowMs < phaseStartMs + duration) break
    phaseStartMs += duration
    phase += 1
  }
  return { phase, phaseStartMs }
}

export function phaseOf(tuple: PhaseTuple, durationsMs: readonly number[], nowMs: number): number {
  return advancePhase(tuple, durationsMs, nowMs).phase
}

export function phaseStartMsOf(tuple: PhaseTuple, durationsMs: readonly number[], nowMs: number): number {
  return advancePhase(tuple, durationsMs, nowMs).phaseStartMs
}

/** Time spent in the tuple's own phase. Never negative, never derived from a local timer. */
export function phaseElapsedMs(tuple: { phaseStartMs: number }, nowMs: number): number {
  return Math.max(0, nowMs - tuple.phaseStartMs)
}

/** Absolute deadline of the tuple's phase. Infinity when the phase never expires. */
export function phaseEndsAtMs(tuple: PhaseTuple, durationsMs: readonly number[]): number {
  const duration = durationOf(tuple, durationsMs)
  return duration > 0 ? tuple.phaseStartMs + duration : Number.POSITIVE_INFINITY
}

export function phaseRemainingMs(tuple: PhaseTuple, durationsMs: readonly number[], nowMs: number): number {
  const endsAtMs = phaseEndsAtMs(tuple, durationsMs)
  if (endsAtMs === Number.POSITIVE_INFINITY) return Number.POSITIVE_INFINITY
  return Math.max(0, endsAtMs - nowMs)
}

/**
 * Edge detector over a derived phase number. Feed it the current phase every
 * frame; it answers with the boundaries to run hooks for.
 *
 * - The first step reports the current phase as entered: a client joining
 *   mid-round must still run "enter wave 7", it has no history to catch up on.
 * - A backwards jump (the server reset the tuple) reports the new phase once,
 *   never the phases in between.
 * - A gap larger than `maxCatchUp` reports only the final phase and counts the
 *   rest as `skipped` — a server that slept through 400 waves must not run 400
 *   wave-start hooks on wake.
 */
export class PhaseWatcher {
  private last: number | null = null

  constructor(private maxCatchUp = 32) {}

  step(phase: number): PhaseAdvance | null {
    const current = Math.trunc(phase)
    if (this.last === null || current < this.last) {
      this.last = current
      return { entered: [current], skipped: 0 }
    }
    if (current === this.last) return null
    const gap = current - this.last
    if (gap > this.maxCatchUp) {
      this.last = current
      return { entered: [current], skipped: gap - 1 }
    }
    const entered: number[] = []
    for (let next = this.last + 1; next <= current; next++) entered.push(next)
    this.last = current
    return { entered, skipped: 0 }
  }

  /** The last reported phase, or null before the first step. */
  current(): number | null {
    return this.last
  }

  reset(): void {
    this.last = null
  }
}
