// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Pool bookkeeping: which instance id is alive on which entity, the hard cap on
// concurrently-alive clones, and the parked set a reusing pool draws from.
//
// Instance ids are the pool's identity across the wire: an outcome entry names a
// clone by id, never by entity. Auto-allocated ids are therefore monotonic and
// never reused — a late `hit {instanceId: 12}` arriving after release must miss,
// not land on whoever took slot 12 next.

export interface PoolSlot<E> {
  entity: E
  instanceId: number
}

export class PoolState<E> {
  private byId = new Map<number, E>()
  private ids = new Map<E, number>()
  private parked: E[] = []
  private auto = 0

  constructor(readonly max: number) {}

  get size(): number {
    return this.byId.size
  }

  get full(): boolean {
    return this.byId.size >= this.max
  }

  /** Next never-used id. Ids climb; the pool cap bounds entities, not ids. */
  nextId(): number {
    this.auto += 1
    return this.auto
  }

  /** Keep auto ids clear of externally supplied ones (plan ids, per-player hashes). */
  observeId(instanceId: number): void {
    if (instanceId > this.auto) this.auto = instanceId
  }

  /** False when the pool is at max or that id is already alive. */
  canClaim(instanceId: number): boolean {
    return !this.full && !this.byId.has(instanceId)
  }

  claim(instanceId: number, entity: E): void {
    this.byId.set(instanceId, entity)
    this.ids.set(entity, instanceId)
    this.observeId(instanceId)
  }

  /** Unbind; returns the freed instance id, or null for an entity this pool never owned. */
  release(entity: E): number | null {
    const instanceId = this.ids.get(entity)
    if (instanceId === undefined) return null
    this.ids.delete(entity)
    this.byId.delete(instanceId)
    return instanceId
  }

  entityOf(instanceId: number): E | null {
    return this.byId.get(instanceId) ?? null
  }

  instanceIdOf(entity: E): number | null {
    return this.ids.get(entity) ?? null
  }

  alive(): E[] {
    return [...this.ids.keys()]
  }

  slots(): PoolSlot<E>[] {
    return [...this.byId].map(([instanceId, entity]) => ({ entity, instanceId }))
  }

  /** Entities kept for reuse (server pools only — their synced id must stay stable). */
  park(entity: E): void {
    if (!this.parked.includes(entity)) this.parked.push(entity)
  }

  unpark(): E | null {
    return this.parked.shift() ?? null
  }

  parkedCount(): number {
    return this.parked.length
  }
}

/**
 * A stable non-negative int for a string key (FNV-1a, 31-bit). Per-player pools
 * derive an instance id from the wallet with it, so every client names the same
 * player's clone identically without exchanging a table.
 */
export function stableId(text: string): number {
  let hash = 0x811c9dc5
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i)
    hash = Math.imul(hash, 0x01000193)
  }
  return (hash >>> 0) % 0x7fffffff
}
