// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Bookkeeping for protectedSync, SDK-free. Two jobs: remember which components
// of which entities carry a server validator (the editor reads this back off
// the log stream to draw observed-authority glyphs), and notice when a
// component class gets its FIRST validator after the server already told
// clients it was alive — the window where a racing client's writes pass
// unvalidated.

export interface ProtectedEntry {
  entity: number
  componentIds: number[]
}

export type ProtectedLogKind = 'registered' | 'late'

export class ProtectedLedger {
  private byEntity = new Map<number, Set<number>>()
  private armed = new Set<number>()
  private sealed = false

  /**
   * Records a registration. `late` lists the component ids that had no
   * validator anywhere before the seal — a per-entity registration for an
   * already-armed component is normal (pools create entities at runtime).
   */
  record(entity: number, componentIds: number[]): { late: number[] } {
    const known = this.byEntity.get(entity) ?? new Set<number>()
    const late: number[] = []
    for (const id of componentIds) {
      known.add(id)
      if (this.sealed && !this.armed.has(id)) late.push(id)
      this.armed.add(id)
    }
    this.byEntity.set(entity, known)
    return { late }
  }

  /** Called once the server is about to announce itself (first heartbeat). */
  seal(): void {
    this.sealed = true
  }

  isSealed(): boolean {
    return this.sealed
  }

  protects(entity: number, componentId: number): boolean {
    return this.byEntity.get(entity)?.has(componentId) === true
  }

  forget(entity: number): void {
    this.byEntity.delete(entity)
  }

  entries(): ProtectedEntry[] {
    return [...this.byEntity].map(([entity, ids]) => ({ entity, componentIds: [...ids] }))
  }
}

/**
 * Peer identity check for the auth server's own writes. Addresses arrive in
 * mixed case from different transports, so compare trimmed and lowercased —
 * and never let an empty address match, which would turn a missing sender into
 * the server itself.
 */
export function isServerPeer(senderAddress: string, serverPeerId: string): boolean {
  const sender = senderAddress.trim().toLowerCase()
  const server = serverPeerId.trim().toLowerCase()
  return sender !== '' && sender === server
}

/** The structured line the editor parses off the Logs SSE stream. */
export function protectedLogLine(kind: ProtectedLogKind, entry: ProtectedEntry): string {
  return `[SERVER] protected-sync ${JSON.stringify({
    kind,
    entity: entry.entity,
    componentIds: entry.componentIds
  })}`
}
