// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Deterministic seeded RNG (mulberry32). The multiplayer pattern: the server
// broadcasts one seed, every client regenerates identical gameplay values from
// it — never stream layouts or timings, reconstruct them.
export type Rng = () => number

export function createRng(seed: number): Rng {
  let s = seed | 0
  return function (): number {
    s |= 0
    s = (s + 0x6d2b79f5) | 0
    let t = Math.imul(s ^ (s >>> 15), 1 | s)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 0x100000000
  }
}

export function rngRange(rng: Rng, min: number, max: number): number {
  return min + rng() * (max - min)
}

export function rngInt(rng: Rng, min: number, maxExclusive: number): number {
  return min + Math.floor(rng() * (maxExclusive - min))
}

export function rngPick<T>(rng: Rng, items: readonly T[]): T {
  return items[rngInt(rng, 0, items.length)]
}
