// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Runner-parity core: how a Script component becomes a live instance.
//
// This mirrors `runScripts` in @dcl/sdk-commands/dist/logic/runtime-script.js,
// which is what constructs PLACED scripts. spawner.ts constructs CLONED scripts,
// and the two must agree field for field — a clone whose `src` or params differ
// from the placed original is a gameplay bug that never shows up as a build
// error. The rules are isolated here, SDK-free, so they can be unit-tested
// against the real runner's source (packages/desktop/src/runtime-spawner.test.ts)
// instead of being re-derived from memory.
//
// The five rules, in the runner's own order:
//   1. src        = the script path's DIRECTORY
//   2. layout     = JSON.parse(layout || '{}')
//   3. params     = Object.values(layout.params).map(action ? callback : value)
//                   — positional, in the params object's insertion order
//   4. the class  = the first function-valued export of the module
//                   (a module exporting `start` is a function-style script instead)
//   5. the key    = `${entity}:${path}` in globalThis.__DCL_SCRIPT_INSTANCES__

export interface ScriptLayoutParam {
  type?: string
  value?: unknown
}

export interface ScriptLayout {
  params?: Record<string, ScriptLayoutParam>
}

/** The `{ entity, action }` shape an 'action' param carries. */
export interface ActionRef {
  entity: number
  action: string
}

export interface ScriptInstance {
  [member: string]: unknown
}

export type ScriptCtor<E> = new (src: string, entity: E, ...params: unknown[]) => ScriptInstance

/** The script's DIRECTORY — what sdk-commands passes as the constructor's `src`. */
export function scriptSrc(path: string): string {
  return path.split('/').slice(0, -1).join('/')
}

/** The __DCL_SCRIPT_INSTANCES__ registry key, so callScriptMethod() reaches clones. */
export function instanceKey(entity: number, path: string): string {
  return `${entity}:${path}`
}

/** `JSON.parse(layout || '{}')`, with a malformed layout reported rather than thrown. */
export function parseScriptLayout(layoutJson: string | undefined): ScriptLayout {
  if (layoutJson === undefined || layoutJson === '') return {}
  const parsed: unknown = JSON.parse(layoutJson)
  return isRecord(parsed) ? (parsed as ScriptLayout) : {}
}

/**
 * Positional constructor params, in the layout's insertion order. `makeAction`
 * builds the callback for 'action' params — it lives in the SDK-facing module
 * because emitting needs @dcl/asset-packs.
 */
export function resolveScriptParams(layout: ScriptLayout, makeAction: (ref: ActionRef) => () => void): unknown[] {
  const params = layout.params
  if (!isRecord(params)) return []
  return Object.values(params).map((param) => {
    if (!isRecord(param)) return undefined
    const value = param.value
    // the runner's exact test: type 'action' AND a truthy object value
    if (param.type === 'action' && value !== null && typeof value === 'object') {
      return makeAction(asActionRef(value))
    }
    return value
  })
}

/** True when the module is a function-style script (`export function start(src, entity, …)`). */
export function isFunctionStyleScript(module: Record<string, unknown>): boolean {
  return typeof module.start === 'function'
}

/** The class the runner would pick: the first function-valued export. */
export function resolveScriptClass<E>(module: Record<string, unknown>): ScriptCtor<E> | null {
  const found = Object.values(module).find((exported) => typeof exported === 'function')
  return found === undefined ? null : (found as ScriptCtor<E>)
}

/**
 * A callable member, bound to its owner — `start`, `update`, and the optional
 * `detach` a pooled clone gets on release. Returns null when the member is not a
 * function, which is how the runner tests for it.
 */
export function methodOf(owner: object, name: string): ((...args: unknown[]) => unknown) | null {
  const member = (owner as Record<string, unknown>)[name]
  if (typeof member !== 'function') return null
  return (member as (...args: unknown[]) => unknown).bind(owner)
}

function asActionRef(value: object): ActionRef {
  const record = value as Record<string, unknown>
  return {
    entity: typeof record.entity === 'number' ? record.entity : 0,
    action: typeof record.action === 'string' ? record.action : ''
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}
