// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Server-private state, SDK-free core. One plain object held in memory,
// repaired on read into the shape `defaults()` declares (normalize-on-read,
// same rule as playerStore), and dirty-tracked by CONTENT rather than by a
// flag — a caller that mutates the object returned by get() still gets
// persisted, which a boolean flag would silently miss.

export interface ServerStoreOptions<T extends object> {
  /** Unique per store: two stores sharing a key would share state without saying so. */
  key: string
  defaults: () => T
}

export class ServerStore<T extends object> {
  private value: T
  private persisted: string | null = null

  constructor(private options: ServerStoreOptions<T>) {
    this.value = options.defaults()
  }

  get key(): string {
    return this.options.key
  }

  /** The live object. Mutating it is visible immediately and still flushes. */
  get(): T {
    return this.value
  }

  /** Field-wise merge. `undefined` values are ignored — they would erase a field. */
  patch(next: Partial<T>): void {
    const target = this.value as Record<string, unknown>
    for (const [field, candidate] of Object.entries(next)) {
      if (candidate === undefined) continue
      target[field] = candidate
    }
  }

  /**
   * Adopt a persisted payload: only fields `defaults()` declares survive, and
   * only when the stored kind still matches. Anything else falls back, so an
   * older schema or a hand-edit in the storage UI cannot crash the server.
   */
  adopt(raw: unknown): void {
    if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) return
    const stored = raw as Record<string, unknown>
    const defaults = this.options.defaults() as Record<string, unknown>
    for (const [field, fallback] of Object.entries(defaults)) {
      const candidate = stored[field]
      defaults[field] = sameKind(candidate, fallback) ? candidate : fallback
    }
    this.value = defaults as T
  }

  /** True when the value differs from what was last persisted. */
  needsFlush(): boolean {
    return encode(this.value) !== this.persisted
  }

  /** The payload to write plus the encoding to record once the write lands. */
  snapshot(): { value: T; encoded: string } {
    return { value: this.value, encoded: encode(this.value) }
  }

  /** Call only after a write actually persisted; a failed write stays dirty. */
  markPersisted(encoded: string): void {
    this.persisted = encoded
  }
}

/**
 * Claims `key` in `claimed`, throwing when it was taken. Two stores under one
 * key share state silently — across prefab copies that is a cross-prefab data
 * leak nobody would ever see in a log.
 */
export function claimStoreKey(claimed: Set<string>, key: string): void {
  if (key.trim() === '') throw new Error('server state needs a non-empty key')
  if (claimed.has(key)) {
    throw new Error(`server state key '${key}' is already in use — give each store its own key`)
  }
  claimed.add(key)
}

function encode(value: object): string {
  return JSON.stringify(value)
}

function sameKind(candidate: unknown, fallback: unknown): boolean {
  if (Array.isArray(fallback)) return Array.isArray(candidate)
  if (Array.isArray(candidate)) return false
  if (fallback === null) return candidate !== undefined
  if (typeof fallback === 'number') return typeof candidate === 'number' && Number.isFinite(candidate)
  return typeof candidate === typeof fallback && candidate !== null
}
