// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Planned spawning: a wave is a pure function of {seed, phase, phaseStartMs,
// configVersion}, materialised locally by every client on the synced clock.
//
// Ported from dead-surge's plannedSpawnSystem, with the room coupling stripped
// and the ids made numeric. Its id scheme (`room_w<wave>_z<seq>`) is what made
// server-side HP tracking possible without the server ever holding an entity, so
// it survives as planInstanceId(phase, index): derived from the tuple, identical
// on every client and on the server, never allocated.
//
// Two invariants the shipped game learned the hard way:
//   - A death that arrives before the spawn does must CANCEL the spawn. A
//     rejoiner reconstructs the whole phase from the tuple, so without sticky
//     suppression they materialise the zombies everyone else already killed.
//   - Draining is catch-up, not replay: entries whose time has passed spawn
//     immediately on the first sync (that IS the rejoin fast-forward), which is
//     why `due()` drains everything at or before now rather than one per tick.

export interface PlanEntryLike {
  instanceId: number
  atMs: number
  init?: Record<string, unknown>
}

export interface PlanTupleLike {
  seed: number
  phase: number
  phaseStartMs: number
  configVersion: number
}

/** Ids of one phase occupy [phase * STRIDE, phase * STRIDE + STRIDE). */
export const PLAN_ID_STRIDE = 100_000

/** How many spawned/suppressed ids stay remembered; older ones can no longer arrive. */
const MAX_TRACKED = 4096

/** The id every client gives spawn #index of `phase`. Not allocated — derived. */
export function planInstanceId(phase: number, index: number): number {
  if (index < 0 || index >= PLAN_ID_STRIDE) {
    throw new Error(`spawn plan index ${index} out of range (0..${PLAN_ID_STRIDE - 1})`)
  }
  return Math.max(0, Math.floor(phase)) * PLAN_ID_STRIDE + Math.floor(index)
}

export function planPhaseOf(instanceId: number): number {
  return Math.floor(instanceId / PLAN_ID_STRIDE)
}

export function planIndexOf(instanceId: number): number {
  return instanceId % PLAN_ID_STRIDE
}

/** Total order: by time, then by id, so every client drains in the same sequence. */
export function sortPlan(entries: PlanEntryLike[]): PlanEntryLike[] {
  return [...entries].sort((a, b) => (a.atMs === b.atMs ? a.instanceId - b.instanceId : a.atMs - b.atMs))
}

/** Identity of a plan. A changed tuple is a new plan; the same tuple must not re-plan. */
export function tupleKey(tuple: PlanTupleLike): string {
  return `${tuple.seed}:${tuple.phase}:${tuple.phaseStartMs}:${tuple.configVersion}`
}

export class PlanQueue {
  private key = ''
  private pending: PlanEntryLike[] = []
  private spawned = new Set<number>()
  private suppressed = new Set<number>()

  /** The tuple this queue is currently planning for; '' before the first sync. */
  get planKey(): string {
    return this.key
  }

  get pendingCount(): number {
    return this.pending.length
  }

  /**
   * Adopt a reconstructed plan. Re-syncing the same key is a no-op, so a consumer
   * may call this every tick. Spawned and suppressed ids survive across plans —
   * they are phase-scoped by construction and a late outcome must still land.
   */
  reset(key: string, entries: PlanEntryLike[]): boolean {
    if (key === this.key) return false
    this.key = key
    this.pending = sortPlan(entries).filter((entry) => !this.spawned.has(entry.instanceId))
    return true
  }

  /**
   * Everything due at nowMs, in plan order, marked spawned. Suppressed ids are
   * dropped. `limit` is the pool's free room: entries past it stay pending rather
   * than being consumed and lost, so a full pool delays a spawn instead of
   * skipping it.
   */
  due(nowMs: number, limit = Number.MAX_SAFE_INTEGER): PlanEntryLike[] {
    const ready: PlanEntryLike[] = []
    while (ready.length < limit && this.pending.length > 0 && this.pending[0].atMs <= nowMs) {
      const entry = this.pending.shift()
      if (entry === undefined) break
      if (this.suppressed.has(entry.instanceId) || this.spawned.has(entry.instanceId)) continue
      this.track(this.spawned, entry.instanceId)
      ready.push(entry)
    }
    return ready
  }

  /** This instance is over: never materialise it, even if its plan entry is still pending. */
  suppress(instanceId: number): void {
    this.track(this.suppressed, instanceId)
    this.pending = this.pending.filter((entry) => entry.instanceId !== instanceId)
  }

  isSuppressed(instanceId: number): boolean {
    return this.suppressed.has(instanceId)
  }

  hasSpawned(instanceId: number): boolean {
    return this.spawned.has(instanceId)
  }

  /** Forget everything (pool released wholesale, or the consumer left the match). */
  clear(): void {
    this.key = ''
    this.pending = []
    this.spawned.clear()
    this.suppressed.clear()
  }

  private track(set: Set<number>, instanceId: number): void {
    set.add(instanceId)
    if (set.size <= MAX_TRACKED) return
    const oldest = set.values().next()
    if (!oldest.done) set.delete(oldest.value)
  }
}
