// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// NTP-style clock offset math (see timeSync.ts for the transport half).
export interface NtpSample {
  offset: number
  rtt: number
}

// t1 client send, t2 server receive, t3 server send, t4 client receive.
export function ntpSample(t1: number, t2: number, t3: number, t4: number): NtpSample {
  return {
    rtt: t4 - t1 - (t3 - t2),
    offset: (t2 - t1 + (t3 - t4)) / 2
  }
}

// Sort by round-trip time, drop the best and worst, average the rest.
// Needs at least 3 samples; fewer returns a plain average.
export function combineSamples(samples: readonly NtpSample[]): number {
  if (samples.length === 0) return 0
  const sorted = [...samples].sort((a, b) => a.rtt - b.rtt)
  const kept = sorted.length >= 3 ? sorted.slice(1, -1) : sorted
  return kept.reduce((sum, s) => sum + s.offset, 0) / kept.length
}
