// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Local Transforms → one world Transform, SDK-free.
//
// A spawn point is usually a child of something — a door, a platform, a prefab
// instance — so its own Transform is only meaningful next to its parents'. A
// copy created by the spawner is a ROOT entity, so the position written on it
// has to be the composed one or it lands wherever the chain's offsets happened
// to add up to.
//
// The composition is the engine's own order, position → rotation → scale:
//   world.position = parent.position + parent.rotation * (parent.scale ∘ local.position)
//   world.rotation = parent.rotation * local.rotation
//   world.scale    = parent.scale ∘ local.scale
// which is the same rule the editor resolves transforms with, so a spawn point
// the creator drags in the viewport spawns where the marker is drawn.

export interface Vec3 {
  x: number
  y: number
  z: number
}

export interface Quat {
  x: number
  y: number
  z: number
  w: number
}

export interface LocalTransform {
  position: Vec3
  rotation: Quat
  scale: Vec3
  /** 0 is the scene root — the walk stops there. */
  parent: number
}

export interface WorldTransform {
  position: Vec3
  rotation: Quat
  scale: Vec3
}

export function identityTransform(): WorldTransform {
  return { position: { x: 0, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0, w: 1 }, scale: { x: 1, y: 1, z: 1 } }
}

/** Hamilton product: `a` then `b` read as "apply b in a's frame". */
export function mulQuat(a: Quat, b: Quat): Quat {
  return {
    x: a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
    y: a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
    z: a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w,
    w: a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z
  }
}

/** v' = v + 2*q.w*(q.xyz × v) + 2*(q.xyz × (q.xyz × v)) */
export function rotateVec(q: Quat, v: Vec3): Vec3 {
  const cx = q.y * v.z - q.z * v.y
  const cy = q.z * v.x - q.x * v.z
  const cz = q.x * v.y - q.y * v.x
  const ux = q.w * cx + (q.y * cz - q.z * cy)
  const uy = q.w * cy + (q.z * cx - q.x * cz)
  const uz = q.w * cz + (q.x * cy - q.y * cx)
  return { x: v.x + 2 * ux, y: v.y + 2 * uy, z: v.z + 2 * uz }
}

/** `chain` is ROOT-FIRST: [outermost parent, …, the entity itself]. */
export function composeWorld(chain: readonly LocalTransform[]): WorldTransform {
  let world = identityTransform()
  for (const local of chain) {
    const scaled = {
      x: local.position.x * world.scale.x,
      y: local.position.y * world.scale.y,
      z: local.position.z * world.scale.z
    }
    const rotated = rotateVec(world.rotation, scaled)
    world = {
      position: {
        x: world.position.x + rotated.x,
        y: world.position.y + rotated.y,
        z: world.position.z + rotated.z
      },
      rotation: mulQuat(world.rotation, local.rotation),
      scale: {
        x: world.scale.x * local.scale.x,
        y: world.scale.y * local.scale.y,
        z: world.scale.z * local.scale.z
      }
    }
  }
  return world
}
