// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Name → zone registry behind zoneBus. SDK-free so the matching, occupancy and
// replay rules are unit-testable; zoneBus.ts is the thin ECS wrapper.
//
// Names are matched case- and whitespace-insensitively. The name is the only
// handle the creator, the script and the AI share, it is typed twice (once in
// the hierarchy, once in a script), and a mismatch fails silently in both
// directions — so 'Front Hall', 'front hall' and ' FRONT HALL ' are one zone.
// The display spelling is kept for tooling that shows the creator their names.

export type ZoneEventKind = 'enter' | 'exit'
export type ZoneListenKind = ZoneEventKind | 'any'

/** (kind, who, zoneEntity) — the raw event before zoneBus adds identity. */
export type ZoneSink<E> = (kind: ZoneEventKind, who: E, zoneEntity: E) => void

interface Source<E> {
  zoneEntity: E
  occupants: () => E[]
}

interface Listener<E> {
  kind: ZoneListenKind
  sink: ZoneSink<E>
}

export function zoneKey(name: string): string {
  return name.trim().toLowerCase()
}

export class ZoneRegistry<E> {
  private sources = new Map<string, Source<E>[]>()
  private display = new Map<string, string>()
  private listeners = new Map<string, Listener<E>[]>()

  /** Several areas may share one name; they behave as a single zone. */
  publish(name: string, zoneEntity: E, occupants: () => E[]): void {
    const key = zoneKey(name)
    if (key === '') return
    this.display.set(key, name.trim())
    const list = this.sources.get(key) ?? []
    const at = list.findIndex((source) => source.zoneEntity === zoneEntity)
    if (at >= 0) list[at] = { zoneEntity, occupants }
    else list.push({ zoneEntity, occupants })
    this.sources.set(key, list)
  }

  unpublish(zoneEntity: E): void {
    for (const [key, list] of [...this.sources]) {
      const kept = list.filter((source) => source.zoneEntity !== zoneEntity)
      if (kept.length === list.length) continue
      if (kept.length > 0) {
        this.sources.set(key, kept)
        continue
      }
      this.sources.delete(key)
      this.display.delete(key)
    }
  }

  /** Display spelling of every published zone, in publication order. */
  names(): string[] {
    return [...this.display.values()]
  }

  /** The spelling the creator typed, or the caller's trimmed input if unpublished. */
  displayName(name: string): string {
    return this.display.get(zoneKey(name)) ?? name.trim()
  }

  /** Everyone inside any area with this name, deduped. */
  occupants(name: string): E[] {
    const found: E[] = []
    for (const source of this.sources.get(zoneKey(name)) ?? []) {
      for (const who of source.occupants()) if (!found.includes(who)) found.push(who)
    }
    return found
  }

  contains(name: string, who: E): boolean {
    for (const source of this.sources.get(zoneKey(name)) ?? []) {
      if (source.occupants().includes(who)) return true
    }
    return false
  }

  subscribe(name: string, kind: ZoneListenKind, sink: ZoneSink<E>): () => void {
    const key = zoneKey(name)
    const listener: Listener<E> = { kind, sink }
    const list = this.listeners.get(key) ?? []
    list.push(listener)
    this.listeners.set(key, list)
    // Script order is not authored, so a consumer routinely starts after the
    // area has already been entered. Replaying occupancy is what makes onZone
    // agree with isInZone instead of waiting for the next crossing.
    if (kind !== 'exit') {
      for (const source of this.sources.get(key) ?? []) {
        for (const who of source.occupants()) sink('enter', who, source.zoneEntity)
      }
    }
    return () => {
      const current = this.listeners.get(key)
      if (!current) return
      const at = current.indexOf(listener)
      if (at >= 0) current.splice(at, 1)
    }
  }

  emit(name: string, kind: ZoneEventKind, who: E, zoneEntity: E): void {
    // snapshot: a handler that unsubscribes itself must not shift the walk
    for (const listener of [...(this.listeners.get(zoneKey(name)) ?? [])]) {
      if (listener.kind === kind || listener.kind === 'any') listener.sink(kind, who, zoneEntity)
    }
  }
}
