// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import {
  PlayerIdentityData,
  Schemas,
  Transform,
  TriggerArea,
  engine,
  type Entity,
  type LastWriteWinElementSetComponentDefinition
} from '@dcl/sdk/ecs'
import { isServer, registerMessages, syncEntity } from '@dcl/sdk/network'
import { AUTH_SERVER_PEER_ID } from '@dcl/sdk/network/message-bus-sync'
import { Storage } from '@dcl/sdk/server'
import { createRpc, type Rpc } from './rpc'
import { markServerReady, serverLifeState, startServerLife, type ServerLifeState } from './serverLife'
import { previewLog, protectSynced } from './protectedSync'
import { serverState, type ServerState } from './serverState'
import { FlushDebouncer } from './playerStore'
import { playerPosition, sceneLocalPosition } from './playerPositions'
import { interval } from './schedule'
import { knowsSpawnable, pool, snapshotRootComponent, spawnableName, type Pool } from './spawner'
import { getServerTime, initTimeSync } from './timeSync'
import { onZone, zoneNames as publishedZones } from './zoneBus'
import { createRng, type Rng } from './pure/rng'
import { zoneKey } from './pure/zoneRegistry'
import {
  GameCore,
  MAX_PREBOOT_REQUESTS,
  WAKING_FLOOD,
  WAKING_FLOOD_NAME,
  callerLabel,
  layoutSeed,
  wakingDropped,
  type CorePorts,
  type ErrorCard,
  type Player,
  type RoundInfo,
  type Vec3,
  type ZoneVolume
} from './pure/gameCore'

// Transport and timing for the creator's `game` object: one rpc namespace
// carrying every request to the Multiplayer Server, one broadcast envelope
// carrying every message back, and the driver both halves share.
// Every rule lives in pure/gameCore.ts, where the harness can reach it.

const GAME_KEY = '__dclGame_v1'
const BROADCAST = 'game.broadcast'
// A revision off the wire is data: a forged huge one would freeze its key for
// the session, since the mirror drops anything at or below what it has seen.
const MAX_REV = 2 ** 30
const clampRev = (rev: number): number => {
  const n = Number(rev)
  return Number.isFinite(n) && n > 0 ? Math.min(Math.floor(n), MAX_REV) : 0
}
const PARTICIPANT = 'game'
// Storage namespaces — creators' durable data lives under these forever.
const SAVED_STORE_KEY = 'game.saved'
const PLAYER_STORE_KEY = 'game'
// serverState stash for the coming round's seed (§11 seed secrecy).
const ROUND_STORE_KEY = 'game.round'
const TRANSFORM_NAME = 'core::Transform'
// The internal zone-claim request: a client detects a crossing locally (only it
// has avatar colliders), the server re-verifies before anything counts.
const ZONE_REQUEST = 'game.zone'
const ZONE_SWEEP_S = 0.25
const SPHERE_MESH = 1
// The Play HUD's Game strip reads this line. serverLife owns the ladder, and
// the editor has no view into the played scene's ECS, so the console is the
// only channel that reaches it — a ladder re-implemented editor-side would be a
// second truth. Client-only: a client is the one copy that can observe whether
// the server is reachable at all.
const LIFE_LINE = '[studio] game-life'
// The mark that tells an error card from an ordinary notice. The Multiplayer
// Server's stdout and stderr reach the editor through one relay, so writing a
// card with console.error proves nothing on that side, and the `name: message`
// shape cannot stand in for it — a kit script's own notice has the same shape.
// Read and stripped by `log-roles.ts` (`PROBLEM_MARKER`); keep the two in step.
const PROBLEM_LINE = '[studio] problem'

// The one funnel every error card leaves by, marker included — a card printed
// past it would read to the editor as an ordinary notice and go uncounted.
function emitCard(card: ErrorCard): void {
  console.error(`${PROBLEM_LINE} [${card.side}] ${card.name}: ${card.message}`)
}

export type { Player }

// Each top-level game.state key rides its own synced entity, so a single write
// stays far from the transport's 12 KB chunk edge and unrelated keys move
// independently. A sibling copy may have defined the component first.
function defineSharedFact() {
  return engine.defineComponent('runtime::SharedFact', {
    key: Schemas.String,
    json: Schemas.String,
    rev: Schemas.Int
  })
}
const SharedFact =
  (engine.getComponentOrNull('runtime::SharedFact') as ReturnType<typeof defineSharedFact> | null) ?? defineSharedFact()

function registerBroadcast() {
  return registerMessages({
    [BROADCAST]: Schemas.Map({ name: Schemas.String, body: Schemas.String, to: Schemas.String })
  })
}
type BroadcastRoom = ReturnType<typeof registerBroadcast>

interface HeldRequest {
  name: string
  json: string
  resolve: (json: string) => void
  reject: (error: Error) => void
}

type LayoutPlan = (rng: Rng, round: RoundInfo) => Vec3[]

interface LayoutSpec {
  planFn: LayoutPlan
  pool: Pool | null
  /** the round id this field was last built for, '' before the first */
  built: string
  warned: boolean
}

interface GameDriver {
  core: GameCore
  rpc: Rpc
  broadcast: BroadcastRoom
  role: 'server' | 'client' | null
  ticking: boolean
  /** every name a request handler registered under, so a late server fork can arm them all */
  names: Set<string>
  /** requests to the server, held while the ladder says waking */
  held: HeldRequest[]
  /** client: the over-full card is printed once per session, not per refusal */
  heldSaid: boolean
  /** server: fact key → its synced entity */
  factEntities: Map<string, Entity>
  /** server: stale snapshot entities awaiting next-tick removal */
  retirals: Entity[]
  /** client: last rev seen per key, to notice a retired fact's entity vanish */
  seenRevs: Map<string, number>
  saved: ServerState<Record<string, unknown>> | null
  /** server: true once the saved store's read landed. A store whose read never
   * landed is empty AND dirty, so flushing it would write {} over the record
   * the creator has stored. */
  savedRead: boolean
  /** server: the next round's seed, stashed server-private until published */
  roundSeed: ServerState<{ nextSeed: number }> | null
  dirtyPlayers: Map<Player, Record<string, unknown>>
  flush: FlushDebouncer
  /** client: zone keys already subscribed on the zone bus */
  watchedZones: Set<string>
  /** server: dt accumulator for the 4 Hz zone sweep */
  sweepAccum: number
  /** client: prefab → its seeded-layout plan, rebuilt per round */
  layouts: Map<string, LayoutSpec>
  /** client: the last ladder state announced to the editor, so only changes print */
  lifeSaid: ServerLifeState | null
  /** server: flush rounds in a row that wrote nothing, so the retry stops instead of looping */
  storeFails: number
  /** server: the give-up line is printed once per fault, never per failed write */
  storeSaid: boolean
}

// Byte-identical copies of this file are still separate module instances, so
// the shared driver is probed by shape — instanceof would reject a sibling's.
function isDriver(value: unknown): value is GameDriver {
  return (
    typeof value === 'object' &&
    value !== null &&
    'core' in value &&
    typeof value.core === 'object' &&
    value.core !== null &&
    'handleRequest' in value.core &&
    typeof (value.core as { handleRequest: unknown }).handleRequest === 'function' &&
    'names' in value &&
    value.names instanceof Set &&
    'held' in value &&
    Array.isArray(value.held)
  )
}

function driver(): GameDriver {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[GAME_KEY]
  if (isDriver(current)) return current
  const created = createDriver()
  globals[GAME_KEY] = created
  return created
}

function createDriver(): GameDriver {
  const d: GameDriver = {
    core: new GameCore(makePorts(() => d)),
    rpc: createRpc('game'),
    broadcast: registerBroadcast(),
    role: null,
    ticking: false,
    names: new Set<string>(),
    held: [],
    heldSaid: false,
    factEntities: new Map<string, Entity>(),
    retirals: [],
    seenRevs: new Map<string, number>(),
    saved: null,
    savedRead: false,
    roundSeed: null,
    dirtyPlayers: new Map<Player, Record<string, unknown>>(),
    flush: new FlushDebouncer(),
    watchedZones: new Set<string>(),
    sweepAccum: 0,
    layouts: new Map<string, LayoutSpec>(),
    lifeSaid: null,
    storeFails: 0,
    storeSaid: false
  }
  return d
}

// rpc's retry budget (~12 s) is shorter than a production cold start (~15 s):
// while the ladder says waking, hold the request — the client tick drains the
// queue once the first heartbeat lands, so a cold start is a spinner, never a
// mystery timeout.
function sendRequest(d: GameDriver, name: string, json: string): Promise<string> {
  if (serverLifeState() === 'waking') {
    // A script asking from update() parks ~41 per second per client for as long
    // as waking lasts, so this end is capped like the server's: over it the
    // NEWEST is refused, which keeps the asks a player is already waiting on.
    if (d.held.length >= MAX_PREBOOT_REQUESTS) {
      if (!d.heldSaid) {
        d.heldSaid = true
        emitCard({ side: 'you', name: WAKING_FLOOD_NAME, message: WAKING_FLOOD })
      }
      return Promise.reject(new Error(wakingDropped(name)))
    }
    return new Promise<string>((resolve, reject) => {
      d.held.push({ name, json, resolve, reject })
    })
  }
  return d.rpc.call<string>(name, json)
}

function makePorts(self: () => GameDriver): CorePorts {
  return {
    now: () => Date.now(),
    // The official answer, read fresh: the platform resolves the role one
    // system after start(), so anything cached at fork time is false for
    // every start() that really did run on the Multiplayer Server.
    isServerNow: () => isServer(),
    sendRequest: (name, json) => sendRequest(self(), name, json),
    sendBroadcast: (name, json, to) => {
      try {
        // {to} is enforced by the transport (the SFU never delivers it to
        // anyone else); the receive-side check is only defence in depth
        const target = to === undefined ? undefined : to.toLowerCase()
        self().broadcast.send(
          BROADCAST,
          { name, body: json, to: target ?? '' },
          target === undefined ? undefined : { to: [target] }
        )
      } catch {
        // transport down — a broadcast is a moment, it fades
      }
    },
    publishFact: (key, json, rev) => {
      const d = self()
      const existing = d.factEntities.get(key)
      if (existing !== undefined) {
        // the entity can be gone underneath us (the SDK does not yet validate
        // an inbound delete), so re-create rather than throwing on every write
        const fact = SharedFact.getMutableOrNull(existing)
        if (fact !== null) {
          fact.json = json
          fact.rev = rev
          return
        }
        d.factEntities.delete(key)
      }
      const entity = engine.addEntity()
      SharedFact.create(entity, { key, json, rev })
      // auto sync id + refuse-all validator, fused: never synced-but-unguarded
      syncEntity(entity, [SharedFact.componentId])
      protectSynced(entity, [SharedFact], () => false)
      d.factEntities.set(key, entity)
    },
    retireFact: (key) => {
      const d = self()
      const entity = d.factEntities.get(key)
      if (entity === undefined) return
      d.factEntities.delete(key)
      // removeEntity waits a tick — never in the frame that republishes (the
      // NetworkEntity survives until the CRDT flush)
      d.retirals.push(entity)
    },
    emitError: emitCard,
    devWarn: (message) => {
      console.log(`[server] ${message}`)
    },
    loadSaved: async () => {
      const d = self()
      const store = savedStore(d)
      await store.restore()
      d.savedRead = true
      return { ...store.get() }
    },
    storeSaved: (key, value) => {
      const d = self()
      savedStore(d).patch({ [key]: value })
      d.flush.mark(Date.now())
    },
    loadPlayerData: async (player) => {
      const raw = await Storage.player.get<unknown>(player, PLAYER_STORE_KEY)
      return typeof raw === 'object' && raw !== null ? { ...(raw as Record<string, unknown>) } : {}
    },
    storePlayerData: (player, data) => {
      const d = self()
      d.dirtyPlayers.set(player, data)
      d.flush.mark(Date.now())
    },
    // Leave checkpoint: the debounce window would outlive the visit, so the
    // record goes out now. Same retry semantics as flushDurable.
    flushPlayerData: (player) => {
      const d = self()
      const data = d.dirtyPlayers.get(player)
      if (data === undefined) return
      void Storage.player.set(player, PLAYER_STORE_KEY, data).then((ok) => {
        if (!ok) {
          storeRoundFailed(d)
          return
        }
        storeRoundOk(d)
        if (d.dirtyPlayers.get(player) === data) d.dirtyPlayers.delete(player)
      })
    },
    dropPlayer: (player) => self().rpc.forget(player),
    findZones: (key) => findZoneVolumes(key),
    playerPosition: (player) => playerPosition(player),
    // The coming round's seed lives in serverState — reading it from a client
    // throws — and only leaves the stash by being published in the tuple, so
    // no client can precompute the next layout (§11 seed secrecy).
    takeNextSeed: () => {
      const store = roundSeedStore(self())
      const seed = store.get().nextSeed
      store.patch({ nextSeed: freshSeed() })
      return seed
    }
  }
}

function savedStore(d: GameDriver): ServerState<Record<string, unknown>> {
  if (d.saved === null) {
    d.saved = serverState<Record<string, unknown>>({ key: SAVED_STORE_KEY, defaults: () => ({}), persist: true })
  }
  return d.saved
}

function freshSeed(): number {
  return Math.floor(Math.random() * 0x7fffffff)
}

function roundSeedStore(d: GameDriver): ServerState<{ nextSeed: number }> {
  if (d.roundSeed === null) {
    d.roundSeed = serverState<{ nextSeed: number }>({ key: ROUND_STORE_KEY, defaults: () => ({ nextSeed: freshSeed() }) })
  }
  return d.roundSeed
}

// A storage host that keeps refusing is a fault to report, not a loop to run
// for the rest of the session: after this many flush ROUNDS in a row land
// nothing, the retry stops re-arming and says so once. Counting rounds and not
// per-player writes is what makes the cap mean "the host is refusing" instead
// of "five players were in the room" — and any write that lands clears the
// count, so a later good round both resumes the retry and can report again.
const STORAGE_TRIES = 5

/** A flush round in which nothing at all was written. */
function storeRoundFailed(d: GameDriver): void {
  d.storeFails += 1
  if (d.storeFails < STORAGE_TRIES) {
    d.flush.mark(Date.now())
    return
  }
  if (d.storeSaid) return
  d.storeSaid = true
  // A card, not a notice: the refusal is the whole point of noticing it, and the
  // Game strip counts only what the marker names.
  emitCard({
    side: 'server',
    name: SAVED_STORE_KEY,
    message:
      `Saved data isn't being stored — the last ${STORAGE_TRIES} attempts to save failed. ` +
      `Check the Multiplayer Server is running, then play again.`
  })
}

/** A write landed: the host is answering again, so the fault is over. */
function storeRoundOk(d: GameDriver): void {
  d.storeFails = 0
  d.storeSaid = false
}

// Write-behind checkpoint: saved and playerData land after the debounce window,
// never per tick — storage writes are capped. A round that writes nothing stays
// dirty and re-arms the window, up to STORAGE_TRIES rounds.
async function flushDurable(d: GameDriver): Promise<void> {
  let wrote = false
  let refused = false
  // A scene using game.saved and no game.playerData has this as its only
  // durable write: ignoring its answer left the store dirty, nothing re-armed
  // the window, and the record was gone at the next sleep with nothing said.
  if (d.saved !== null && d.savedRead) {
    // a host that throws is a host that refused
    const outcome = await d.saved.flush().catch(() => 'refused' as const)
    if (outcome === 'stored') wrote = true
    else if (outcome === 'refused') refused = true
  }
  for (const [player, data] of [...d.dirtyPlayers]) {
    const ok = await Storage.player.set(player, PLAYER_STORE_KEY, data)
    if (!ok) {
      refused = true
      continue
    }
    wrote = true
    if (d.dirtyPlayers.get(player) === data) d.dirtyPlayers.delete(player)
  }
  if (wrote) {
    storeRoundOk(d)
    if (refused) d.flush.mark(Date.now()) // one player's record was refused, not the host
    return
  }
  if (refused) storeRoundFailed(d)
}

// Every request rides the one rpc namespace; the method map is per-name, so a
// handler can arm at any time. The player's durable record is restored before
// their first handler runs, so playerData(p).get() never races the load.
function armRequest(d: GameDriver, name: string): void {
  d.rpc.handle(name, (body, from) => {
    const player = from.toLowerCase()
    const json = typeof body === 'string' ? body : JSON.stringify(body ?? null)
    return d.core.restorePlayerData(player).then(() => d.core.handleRequest(name, json, player))
  })
}

function myAddress(): string {
  return PlayerIdentityData.getOrNull(engine.PlayerEntity)?.address.toLowerCase() ?? ''
}

type NameValue = { value: string }
type NameComponent = LastWriteWinElementSetComponentDefinition<NameValue>

// A sibling copy of a runtime module may already have defined it.
function nameComponent(): NameComponent {
  const existing = engine.getComponentOrNull('core-schema::Name')
  if (existing !== null) return existing as NameComponent
  return engine.defineComponent('core-schema::Name', { value: Schemas.String })
}

// Zones are resolved by NAME, matched the way zoneBus matches on the client
// (trimmed, case-insensitive) — the name is the only id a zone has. Several
// areas may share a name; being inside any of them is being inside the zone.
function findZoneVolumes(key: string): ZoneVolume[] {
  const found: ZoneVolume[] = []
  if (key === '') return found
  const names = nameComponent()
  for (const [entity, name] of engine.getEntitiesWith(names, TriggerArea)) {
    if (zoneKey(name.value) !== key) continue
    const transform = Transform.getOrNull(entity)
    // Rotation and scale are the zone's own; the editor places zones at the
    // scene root, and only the center needs the parent chain composed.
    const center = sceneLocalPosition(entity)
    if (transform === null || center === null) continue
    found.push({
      shape: TriggerArea.getOrNull(entity)?.mesh === SPHERE_MESH ? 'sphere' : 'box',
      center,
      rotation: transform.rotation,
      scale: transform.scale
    })
  }
  return found
}

// Headless presence: SDK onEnterScene/getPlayer never fire on the Multiplayer
// Server, but synced PlayerIdentityData entities do arrive — the identity set
// IS the roster. The server's own PlayerEntity is not a player.
function presentAddresses(): Player[] {
  const seen = new Set<Player>()
  for (const [entity, identity] of engine.getEntitiesWith(PlayerIdentityData)) {
    if (entity === engine.PlayerEntity) continue
    const address = (identity.address ?? '').toLowerCase()
    if (address !== '') seen.add(address)
  }
  return [...seen]
}

function armZoneClaims(d: GameDriver): void {
  d.rpc.handle(ZONE_REQUEST, (body, from) => {
    const raw = typeof body === 'string' ? body : ''
    let claim: Record<string, unknown> = {}
    try {
      const parsed: unknown = JSON.parse(raw)
      if (typeof parsed === 'object' && parsed !== null) claim = parsed as Record<string, unknown>
    } catch {
      // an empty claim fails the name check below
    }
    const zone = typeof claim.zone === 'string' ? claim.zone : ''
    const kind = claim.kind === 'exit' ? 'exit' : 'enter'
    return d.core.zoneClaim(zone, kind, from.toLowerCase())
  })
}

// The client watches every Trigger Area placed in the scene, not the ones a
// script happened to register for: the zone bus is published by the Trigger
// Area item itself, so the side game.onEnterArea was registered on stops
// mattering and it can live inside if (isServer()) like every other hook. Areas
// published after boot join the watch list on the tick they appear.
function watchPublishedZones(d: GameDriver): void {
  const names = publishedZones()
  if (names.length === d.watchedZones.size) return
  for (const zone of names) watchZone(d, zone)
}

function watchZone(d: GameDriver, zone: string): void {
  const key = zoneKey(zone)
  if (key === '' || d.watchedZones.has(key)) return
  d.watchedZones.add(key)
  onZone(zone, 'any', (event) => {
    if (!event.local) return
    void claimZone(d, zone, event.kind)
  })
}

// A refused claim is an answer (outside, or an area no script listens to) — the
// server-side callback simply never fires; there is nothing to surface.
async function claimZone(d: GameDriver, zone: string, kind: 'enter' | 'exit'): Promise<void> {
  try {
    await sendRequest(d, ZONE_REQUEST, JSON.stringify({ zone, kind }))
  } catch {
    // refused or transport down — deliberately quiet
  }
}

function armTick(d: GameDriver): void {
  if (d.ticking) return
  d.ticking = true
  engine.addSystem(
    (dt) => {
      const live = driver()
      if (live.role === null) {
        // the platform has resolved the role by the first tick — fork now, and
        // skip the role tick this frame so boot's retirals wait a full tick
        fork(live)
        return
      }
      if (live.role === 'server') serverTick(live, dt)
      else clientTick(live)
    },
    undefined,
    'runtime-game'
  )
}

function fork(d: GameDriver): void {
  const server = isServer()
  d.role = server ? 'server' : 'client'
  initTimeSync()
  startServerLife(PARTICIPANT)
  if (server) {
    // Per-entity guards only cover entities this run created: the SDK mints a
    // fresh entity for an id it has never seen, and an unguarded component is
    // accepted by default — so without this a modified client could publish a
    // shared fact of its own. Component-global, armed once, refusing anyone
    // who is not the server itself (the serverLife precedent).
    SharedFact.validateBeforeChange(
      ({ senderAddress }) => senderAddress.toLowerCase() === AUTH_SERVER_PEER_ID
    )
    for (const name of d.names) armRequest(d, name)
    armZoneClaims(d)
    // the CRDT snapshot outlives the isolate: adopt what survived, then boot
    // retires it (state resets when the server sleeps) and republishes fresh
    const adopted: Array<{ key: string; json: string; rev: number }> = []
    for (const [entity] of engine.getEntitiesWith(SharedFact)) {
      const fact = SharedFact.get(entity)
      adopted.push({ key: fact.key, json: fact.json, rev: clampRev(fact.rev) })
      d.factEntities.set(fact.key, entity)
    }
    // Readiness is the heartbeat clients read the life ladder from, so it is
    // answered only by a boot that finished. A boot that stopped halfway has
    // already reported its card and opened its request gate; withholding the
    // beat is what keeps the Game strip from calling that server running.
    void d.core.bootServer(adopted, presentAddresses()).then(
      () => markServerReady(PARTICIPANT),
      () => {}
    )
  } else {
    d.broadcast.onMessage(BROADCAST, (msg) => {
      if (msg.to !== '' && msg.to !== myAddress()) return
      d.core.handleBroadcast(msg.name, msg.body)
    })
  }
}

function serverTick(d: GameDriver, dt: number): void {
  for (const entity of d.retirals.splice(0)) engine.removeEntity(entity)
  d.core.flushState()
  d.core.presentPlayers(presentAddresses())
  d.sweepAccum += dt
  if (d.sweepAccum >= ZONE_SWEEP_S) {
    d.sweepAccum = 0
    d.core.sweepZones(Date.now())
  }
  if (d.flush.isDue(Date.now())) {
    d.flush.clear()
    void flushDurable(d)
  }
}

function clientTick(d: GameDriver): void {
  watchPublishedZones(d)
  const present = new Set<string>()
  for (const [entity] of engine.getEntitiesWith(SharedFact)) {
    const fact = SharedFact.get(entity)
    const rev = clampRev(fact.rev)
    present.add(fact.key)
    d.core.applyFact(fact.key, fact.json, rev)
    d.seenRevs.set(fact.key, rev)
  }
  for (const [key, rev] of [...d.seenRevs]) {
    if (present.has(key)) continue
    // the server retired the fact's entity (boot wipe) — the mirror follows
    d.seenRevs.delete(key)
    d.core.applyRetire(key, rev + 1)
  }
  const life = serverLifeState()
  if (life !== d.lifeSaid) {
    d.lifeSaid = life
    previewLog(`${LIFE_LINE} ${life}`)
  }
  if (d.held.length > 0 && life !== 'waking') {
    for (const held of d.held.splice(0)) {
      d.rpc.call<string>(held.name, held.json).then(held.resolve, held.reject)
    }
  }
  layoutTick(d)
}

// Layouts are client-built: every client reconstructs the same field from the
// round tuple (one per-prefab rng stream off the round's seed), so a late
// joiner fast-forwards by arithmetic — the first build IS the current round,
// never a replay — and the server materialises nothing.
//
// The trigger is the round ID, not its number: a client outlives the server's
// sleep, and the number it counts from starts again at 1 on the other side. On
// the number, this wake's round 1 reads as the same round as the last wake's,
// and the field would stand there built from a seed nobody is playing anymore.
function layoutTick(d: GameDriver): void {
  if (d.layouts.size === 0) return
  const round = d.core.round
  if (round.id === '') return
  for (const [prefab, spec] of [...d.layouts]) {
    if (spec.built === round.id) continue
    spec.built = round.id
    replanLayout(d, prefab, spec, round)
  }
}

function replanLayout(d: GameDriver, prefab: string, spec: LayoutSpec, round: RoundInfo): void {
  // Scripts address a prefab by an id the creator never typed, so every line
  // below names it the way the Prefabs tab does — and when the registry cannot
  // name it at all, the message says so instead of printing the id at someone.
  const named = spawnableName(prefab)
  if (spec.pool === null) {
    try {
      spec.pool = pool(prefab, 'seeded')
    } catch (e) {
      // keep the registration: the message names the fix, and dropping it here
      // meant one bad round silently ended that layout for the whole session
      if (!spec.warned) {
        spec.warned = true
        // two different faults: a prefab this project no longer has, and one
        // already pooled another way — only the second has a cause to quote
        console.error(
          knowsSpawnable(prefab)
            ? `[you] game.layout('${named ?? prefab}'): ${e instanceof Error ? e.message : String(e)}`
            : `[you] game.layout: this script lays out a prefab that is no longer in this project. ` +
                `Pick the prefab again in the inspector, then save the script.`
        )
      }
      return
    }
  }
  const label = named ?? prefab
  // plan BEFORE releasing: a plan that throws must not leave the field empty
  let spots: Vec3[]
  try {
    spots = spec.planFn(createRng(layoutSeed(round.seed, prefab)), round)
  } catch (e) {
    console.error(`[you] layout('${label}'): ${e instanceof Error ? e.message : String(e)}`)
    return
  }
  spec.pool.releaseAll()
  // keep the authored rotation and scale, place at the planned spot
  const authored = snapshotRootComponent(prefab, TRANSFORM_NAME)
  const base = typeof authored === 'object' && authored !== null ? (authored as Record<string, unknown>) : {}
  for (let i = 0; i < spots.length; i++) {
    const at = spots[i]
    try {
      const spawned = spec.pool.acquire(i, { [TRANSFORM_NAME]: { ...base, position: { x: at.x, y: at.y, z: at.z } } })
      if (spawned === null) break // pool at max: the plan asked for more copies than the prefab allows
    } catch (e) {
      // one copy's script crashing must not cost the rest of the field
      console.error(`[you] layout('${label}') #${i}: ${e instanceof Error ? e.message : String(e)}`)
    }
  }
}

// One handler per name: a re-registration from the same script must replace (a
// prefab placed twice shares one handler) while a second script claiming the
// name must report. The call site is the only script identity that exists at
// runtime — best effort: a bundle that flattens filenames degrades to replace
// semantics.
function scriptId(): string {
  const label = callerLabel()
  return label === '' ? 'scene' : label
}

export const game = {
  /**
   * Runs once when the Multiplayer Server wakes up (not per player, not per
   * round). It is the only hook that runs after saved data has loaded, so
   * game.saved read in start() finds nothing and read here finds everything.
   */
  onReady(fn: () => void | Promise<void>): void {
    driver().core.onReady(fn)
  },
  /** Facts every player agrees on; a player who joins late sees them automatically. */
  get state(): Record<string, unknown> {
    return driver().core.state
  },
  /** Changes the synced state. Only the server can call it. */
  setState(patch: Record<string, unknown>): void {
    driver().core.setState(patch)
  },
  /** Every client, including players who join late. */
  onStateChange(listener: (changed: Record<string, unknown>) => void): void {
    driver().core.onStateChange(listener)
  },
  /**
   * Asks the server and resolves with what game.onRequest returned. Runs on
   * the client; it retries a dropped message for you.
   */
  request<T = unknown>(name: string, data?: unknown): Promise<T> {
    return driver().core.request(name, data) as Promise<T>
  },
  /**
   * Answers what a player asks. Runs on the server, and `player` is the
   * wallet the connection proves — a payload can never forge it.
   */
  onRequest<T = unknown>(name: string, fn: (data: T, player: Player) => unknown | Promise<unknown>): void {
    const d = driver()
    d.names.add(name)
    d.core.onRequest(name, fn as (data: unknown, player: Player) => unknown, scriptId())
    if (d.role === 'server') armRequest(d, name)
  },
  /**
   * Tells every player at once, or one player with `to`. It is a moment: shown
   * once, then gone — players who join later never see it, so lasting facts go
   * in game.state. Runs on the server.
   */
  broadcast(name: string, data?: unknown, to?: Player): void {
    driver().core.broadcast(name, data, to)
  },
  /**
   * Hears what the server broadcasts. Runs on the client, and every script
   * listening for that name hears it. Returns a function that stops listening.
   */
  onBroadcast<T = unknown>(name: string, fn: (data: T) => void): () => void {
    return driver().core.onBroadcast(name, fn as (data: unknown) => void)
  },
  /** The shared clock — the same number on the server and on every client. */
  now(): number {
    return Number(getServerTime())
  },
  /** Runs on the server when a player arrives. */
  onPlayerJoin(fn: (player: Player) => void | Promise<void>): void {
    driver().core.onPlayerJoin(fn)
  },
  /** Runs on the server when a player leaves — their player data is saved right after. */
  onPlayerLeave(fn: (player: Player) => void | Promise<void>): void {
    driver().core.onPlayerLeave(fn)
  },
  /**
   * Runs on the server when a player enters the Trigger Area with this name —
   * the server re-checks their real position before it counts.
   */
  onEnterArea(zone: string, fn: (player: Player) => void | Promise<void>): void {
    driver().core.onEnterArea(zone, fn)
  },
  /** Feet, about 10 times per second — for generous checks only. */
  positionOf(player: Player): Vec3 | null {
    return driver().core.positionOf(player)
  },
  /**
   * The current round — id, number, seed, and when it started. Nothing has
   * started yet while id is '' and number is 0.
   *
   * `round.id` is this round and no other, forever: compare it with ===, keep
   * it in game.saved or game.playerData, print it in a log. `round.number`
   * counts 1, 2, 3… inside one wake of the Multiplayer Server — it starts
   * again at 1 after the server sleeps, so a number written down before the
   * sleep would read as the current round once it wakes.
   */
  get round(): RoundInfo {
    return driver().core.round
  },
  /** Starts the next round for everyone — a fresh id and seed, every layout rebuilds. Only the server can call it. */
  newRound(): RoundInfo {
    return driver().core.newRound()
  },
  /** Runs on the server when a round starts (round 1 included) — reset state here; clients follow through game.onStateChange. */
  onRoundStart(fn: (round: RoundInfo) => void | Promise<void>): void {
    driver().core.onRoundStart(fn)
  },
  /**
   * Each player's client builds its own copies from the round's seed — the
   * layout is identical for all, with zero messages. The callback gets
   * (rng, round) and nothing else, so it cannot diverge; it re-runs on every
   * new round.
   */
  layout(prefab: string, positions: (rng: Rng, round: RoundInfo) => Vec3[]): void {
    const d = driver()
    const existing = d.layouts.get(prefab)
    // a prefab placed twice re-registers the same plan: replace, like onRequest
    if (existing !== undefined) existing.planFn = positions
    else d.layouts.set(prefab, { planFn: positions, pool: null, built: '', warned: false })
    // the plan is only "the same everywhere" on a shared clock (the spawner rule)
    initTimeSync()
  },
  /** Runs every `seconds` seconds on whichever side you write it — the timer starts fresh when that side starts. */
  every(seconds: number, fn: () => void | Promise<void>): void {
    interval(seconds, () => {
      const d = driver()
      // the server's timer waits for boot: a hook firing before onReady would
      // read saved data that has not loaded yet
      if (d.role === 'server' && !d.core.booted()) return
      void d.core.runEvery(fn)
    })
  },
  /** Survives restarts and re-publishes, unlike game.state. Only the server reads or writes it. */
  saved: {
    get<T = unknown>(key: string): T | undefined {
      return driver().core.saved.get(key) as T | undefined
    },
    set(key: string, value: unknown): void {
      driver().core.saved.set(key, value)
    }
  },
  /** One durable record per wallet, forever. set patches top-level keys. */
  playerData<T extends Record<string, unknown> = Record<string, unknown>>(
    player: Player
  ): { get(): Partial<T>; set(patch: Partial<T>): void } {
    return driver().core.playerData(player) as { get(): Partial<T>; set(patch: Partial<T>): void }
  }
}

/**
 * The entities dragged under this one, in the order they were added — the same
 * order on the server and on every client. Use it for the group a piece owns:
 * spawn points, board faces, floors.
 */
export function childrenOf(parent: Entity): Entity[] {
  const out: Entity[] = []
  for (const [entity, transform] of engine.getEntitiesWith(Transform)) {
    if (transform.parent === parent) out.push(entity)
  }
  return out.sort((a, b) => a - b)
}

armTick(driver())
