// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import { Storage } from '@dcl/sdk/server'
import { normalizeVersioned, type Versioned } from './pure/normalize'

// Server-only write-behind store over Storage.player: per-wallet state lives in
// memory, is repaired on read (normalize-on-read), and is flushed at
// checkpoints — round end, player leave, debounced autosave — never per tick
// (storage writes are capped; excess writes fail).
//
// Storage.set resolves false when a write did not persist: failed keys STAY
// dirty so the next flush retries them.
//
// DEBOUNCED FLUSH. A round writes the same player's row dozens of times a
// second; the storage quota is the scarce resource, so mutations only ARM a
// flush. It lands after `debounceMs` of quiet, or at `maxDelayMs` since the
// oldest un-flushed mutation — whichever comes first, so a continuously busy
// round still checkpoints instead of holding everything until it ends. Drive it
// from a system:
//
//   engine.addSystem(() => { void store.flushIfDue() })      // returns null when nothing is due
//   await store.flushNow()                                   // round end / player leave
//
// ONE KEY, ONE STORE. `options.key` is the Storage key namespace. Two stores
// sharing one key overwrite each other's rows with a half-shaped value, which
// only shows up as data loss days later — so the second construction THROWS.
// The claim is anchored on globalThis (every prefab carries its own copy of
// this file, so module scope would not see the collision) and released with
// releasePlayerStoreKey when a script deliberately rebuilds its store.

const KEYS_KEY = '__dclPlayerStoreKeys_v1'

export interface FlushPolicy {
  /** quiet period after the newest mutation before the write goes out */
  debounceMs: number
  /** hard ceiling measured from the oldest un-flushed mutation */
  maxDelayMs: number
}

export const DEFAULT_FLUSH_POLICY: FlushPolicy = { debounceMs: 3_000, maxDelayMs: 15_000 }

/** The debounce decision, as pure state — no clock of its own, no timers. */
export class FlushDebouncer {
  private firstMarkMs: number | null = null
  private lastMarkMs: number | null = null

  constructor(private policy: FlushPolicy = DEFAULT_FLUSH_POLICY) {}

  mark(nowMs: number): void {
    if (this.firstMarkMs === null) this.firstMarkMs = nowMs
    this.lastMarkMs = nowMs
  }

  pending(): boolean {
    return this.firstMarkMs !== null
  }

  isDue(nowMs: number): boolean {
    if (this.firstMarkMs === null || this.lastMarkMs === null) return false
    return nowMs - this.lastMarkMs >= this.policy.debounceMs || nowMs - this.firstMarkMs >= this.policy.maxDelayMs
  }

  clear(): void {
    this.firstMarkMs = null
    this.lastMarkMs = null
  }
}

export interface PlayerStoreOptions<T extends Versioned> {
  /** Storage key, unique per store — two stores (or two prefab copies) must not share one. */
  key: string
  schemaVersion: number
  defaults: () => T
  /** Field-by-field repair of a current-version value; unknown versions fall back to defaults. */
  repair: (value: Partial<T>, defaults: T) => T
  /** Overrides for the debounce window; omitted fields keep DEFAULT_FLUSH_POLICY. */
  flush?: Partial<FlushPolicy>
  /** Clock seam, for tests. */
  now?: () => number
}

export class PlayerStore<T extends Versioned> {
  private cache = new Map<string, T>()
  private dirty = new Set<string>()
  private debouncer: FlushDebouncer
  private inFlight: Promise<string[]> | null = null
  private now: () => number

  constructor(private options: PlayerStoreOptions<T>) {
    this.debouncer = new FlushDebouncer({ ...DEFAULT_FLUSH_POLICY, ...options.flush })
    this.now = options.now ?? Date.now
  }

  get key(): string {
    return this.options.key
  }

  /** Load (or return cached) state for a player. Server-only. */
  async load(address: string): Promise<T> {
    const key = address.toLowerCase()
    const cached = this.cache.get(key)
    if (cached) return cached
    const raw = await Storage.player.get<unknown>(key, this.options.key)
    const value = normalizeVersioned(raw, this.options.schemaVersion, this.options.defaults, this.options.repair)
    this.cache.set(key, value)
    if (raw === null) this.markDirty(key) // first save writes the canonical shape
    return value
  }

  /** In-memory state, if loaded. */
  get(address: string): T | null {
    return this.cache.get(address.toLowerCase()) ?? null
  }

  /** Mutate in memory and arm a flush. Persistence happens at the next checkpoint. */
  mutate(address: string, mutator: (value: T) => void): boolean {
    const key = address.toLowerCase()
    const value = this.cache.get(key)
    if (!value) return false
    mutator(value)
    this.markDirty(key)
    return true
  }

  /** Arm a flush for a player mutated through a reference taken from get(). */
  markDirty(address: string): void {
    this.dirty.add(address.toLowerCase())
    this.debouncer.mark(this.now())
  }

  /** Flush one player. Returns whether the write persisted; failures stay dirty. */
  async save(address: string): Promise<boolean> {
    const key = address.toLowerCase()
    const value = this.cache.get(key)
    if (!value) return true
    const ok = await Storage.player.set(key, this.options.key, value)
    if (ok) this.dirty.delete(key)
    return ok
  }

  /** Flush every dirty player. Returns the addresses that failed (and stay dirty). */
  async saveDirty(): Promise<string[]> {
    const failed: string[] = []
    for (const key of [...this.dirty]) {
      if (!(await this.save(key))) failed.push(key)
    }
    return failed
  }

  /**
   * The autosave tick: writes only when the debounce window has closed and no
   * flush is already in flight. Returns null when there is nothing to do, so a
   * caller can `void store.flushIfDue()` every frame.
   */
  flushIfDue(nowMs = this.now()): Promise<string[]> | null {
    if (this.inFlight) return null
    if (this.dirty.size === 0) {
      this.debouncer.clear()
      return null
    }
    if (!this.debouncer.isDue(nowMs)) return null
    return this.flushNow()
  }

  /** Checkpoint now (round end, player leave). Coalesces with a flush already in flight. */
  flushNow(): Promise<string[]> {
    if (this.inFlight) return this.inFlight
    this.debouncer.clear()
    const run = this.saveDirty().then(
      (failed) => {
        this.inFlight = null
        if (failed.length > 0) this.debouncer.mark(this.now()) // retry after the next window
        return failed
      },
      (error: unknown) => {
        this.inFlight = null
        this.debouncer.mark(this.now())
        throw error
      }
    )
    this.inFlight = run
    return run
  }

  /** Checkpoint for player-leave: flush, then drop from memory (only if persisted). */
  async saveAndEvict(address: string): Promise<boolean> {
    const key = address.toLowerCase()
    const ok = await this.save(key)
    if (ok) this.cache.delete(key)
    return ok
  }

  get dirtyCount(): number {
    return this.dirty.size
  }

  /** True when mutations are waiting for the debounce window to close. */
  flushPending(): boolean {
    return this.debouncer.pending()
  }
}

export function createPlayerStore<T extends Versioned>(options: PlayerStoreOptions<T>): PlayerStore<T> {
  claimStoreKey(options.key)
  return new PlayerStore(options)
}

/** Frees a claimed key so a script can deliberately rebuild its store. */
export function releasePlayerStoreKey(key: string): void {
  claimedKeys().delete(key)
}

function claimStoreKey(key: string): void {
  const keys = claimedKeys()
  if (keys.has(key)) {
    throw new Error(
      `playerStore key "${key}" is already claimed in this scene. Give each store its own key (namespace it by board, prefab or instance name) — two stores on one key overwrite each other's rows.`
    )
  }
  keys.add(key)
}

// Anchored on globalThis, probed by shape: two prefabs carry two copies of this
// file, so a module-scope Set would never see the collision it exists to catch.
function claimedKeys(): Set<string> {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[KEYS_KEY]
  if (isKeySet(current)) return current
  const created = new Set<string>()
  globals[KEYS_KEY] = created
  return created
}

function isKeySet(value: unknown): value is Set<string> {
  return (
    typeof value === 'object' &&
    value !== null &&
    'has' in value &&
    typeof value.has === 'function' &&
    'add' in value &&
    typeof value.add === 'function' &&
    'delete' in value &&
    typeof value.delete === 'function'
  )
}
