// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import { engine, PlayerIdentityData, Transform, type Entity } from '@dcl/sdk/ecs'
import { Vector3 } from '@dcl/sdk/math'

// Scene-local positions for every avatar the scene can see.
//
// The engine hands a scene two different coordinate frames and does not say so.
// engine.PlayerEntity's Transform is already scene-local (the renderer subtracts
// the scene origin before sending it), while every remote avatar entity is
// parented to the reserved WORLD_ORIGIN entity and carries WORLD coordinates.
// Comparing the two only looks correct at base parcel 0,0 — which is the only
// reason the three source games got away with mixing them. Resolving the parent
// chain converts both frames once, here, and is also correct if a future engine
// build reparents avatars somewhere else.
//
// Positions are FEET, not eyes. Client-side only in practice: a headless server
// never builds avatar entities, so this returns [] there (see rpc.ts for the
// authority pattern that actually works server-side).

const MAX_PARENT_DEPTH = 8

export interface PlayerPosition {
  entity: Entity
  /** Lowercased wallet — the same form context.from arrives in. */
  address: string
  position: Vector3
  /** True for this viewer's own avatar. */
  local: boolean
}

export function playerPositions(): PlayerPosition[] {
  const found: PlayerPosition[] = []
  const seen = new Set<string>()
  for (const [entity, identity] of engine.getEntitiesWith(PlayerIdentityData, Transform)) {
    // A PLAYER entity exists before its profile arrives; an addressless one is a
    // phantom that would match every wallet comparison against ''.
    const address = (identity.address ?? '').toLowerCase()
    if (address === '' || seen.has(address)) continue
    const position = sceneLocalPosition(entity)
    if (!position) continue
    seen.add(address)
    found.push({ entity, address, position, local: entity === engine.PlayerEntity })
  }
  return found
}

export function playerPosition(address: string): Vector3 | null {
  const wanted = address.toLowerCase()
  for (const player of playerPositions()) if (player.address === wanted) return player.position
  return null
}

export function localPlayerPosition(): Vector3 | null {
  return sceneLocalPosition(engine.PlayerEntity)
}

/** Resolve an entity's position in the scene's own frame, walking the parent chain to the root. */
export function sceneLocalPosition(entity: Entity): Vector3 | null {
  const transform = Transform.getOrNull(entity)
  if (!transform) return null
  let position = Vector3.create(transform.position.x, transform.position.y, transform.position.z)
  let parent = transform.parent
  for (let depth = 0; depth < MAX_PARENT_DEPTH; depth++) {
    if (parent === undefined || parent === engine.RootEntity) return position
    const parentTransform = Transform.getOrNull(parent)
    if (!parentTransform) return position
    const rotated = Vector3.rotate(position, parentTransform.rotation)
    position = Vector3.add(
      Vector3.create(
        rotated.x * parentTransform.scale.x,
        rotated.y * parentTransform.scale.y,
        rotated.z * parentTransform.scale.z
      ),
      parentTransform.position
    )
    parent = parentTransform.parent
  }
  return position // depth cap: a parent cycle must not hang the frame
}
