// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import { type Entity } from '@dcl/sdk/ecs'
import { isServer, syncEntity } from '@dcl/sdk/network'
import { AUTH_SERVER_PEER_ID } from '@dcl/sdk/network/message-bus-sync'
import { getRealm } from '~system/Runtime'
import { ProtectedLedger, isServerPeer, protectedLogLine, type ProtectedEntry } from './pure/protectedFields'

// The one way to publish a server-owned entity. It fuses the three steps that
// are only correct together — create the components, sync them under a stable
// id, arm a validator on each — so there is no order to get wrong and no
// entity that is synced but unguarded for a frame. (protectSynced below is the
// same guard for an entity something else already synced: the spawner's 'server'
// pools, whose clones take an auto-assigned id instead of a pinned one.)
//
//   protectedSync({
//     entity, syncId: SLOT_SYNC_ID,
//     components: [SlotPick],
//     validate: ({ value, from }) => false            // clients may not write
//   })
//
// `validate` judges CLIENT requests only: the auth server's own writes are
// accepted before it is consulted, so a validator that returns false is the
// plain "server-owned, read-only to everyone else" case.
//
// Server-only: validators exist nowhere else, so calling this on a client
// throws rather than pretending to protect anything.
//
// Registration order. A component's FIRST validator must be armed before the
// server announces itself (serverLife's first heartbeat) — after that, a
// racing client's write reaches an unguarded component. Whoever emits that
// heartbeat calls sealProtectedRegistration(); a later first-time registration
// logs `[SERVER] protected-sync {"kind":"late",…}`. Per-entity registrations
// after the seal are normal — pools create entities while the game runs.
//
// Observed authority. Every registration is recorded and, while a creator is
// playing their own scene (preview or a realm on this machine — see
// isDevRealm), emitted as a structured `[SERVER] protected-sync {…}` line that
// the editor parses off the Logs stream to draw its observed-authority view.
//
// The registry is anchored on globalThis: every prefab carries its own copy of
// this file, and two ledgers would each see half the truth.

const SYNC_KEY = '__dclProtectedSync_v1'
const QUEUE_LIMIT = 64

export interface ProtectedChange {
  entity: Entity
  component: unknown
  value: unknown
  from: string
}

export interface ProtectedSyncOptions {
  entity: Entity
  /** Stable enum id, so every peer agrees which entity this is across restarts. */
  syncId: number
  /** Component definitions to create, sync and guard. */
  components: unknown[]
  /** Judges client-originated writes; the server's own writes never reach it. */
  validate: (change: ProtectedChange) => boolean
}

export function protectedSync(options: ProtectedSyncOptions): void {
  if (!isServer()) {
    throw new Error('protectedSync is server-only — a client cannot validate anything')
  }

  const components = options.components.map(asProtectedComponent)
  const componentIds: number[] = []
  for (const component of components) {
    if (!component.has(options.entity)) component.create(options.entity)
    componentIds.push(component.componentId)
  }

  syncEntity(options.entity, componentIds, options.syncId)
  protectSynced(options.entity, components, options.validate)
}

/**
 * The guard half of protectedSync, for an entity that is ALREADY synced — the
 * spawner's 'server' pools, whose clones take an auto-assigned sync id rather
 * than a pinned one. Arms the validator on each component and records the
 * registration in the same ledger, so a pooled entity shows up in the
 * observed-authority stream like every other server-owned one.
 *
 * Server-only, same as protectedSync: there is nothing to validate on a client.
 */
export function protectSynced(
  entity: Entity,
  components: unknown[],
  validate: (change: ProtectedChange) => boolean
): void {
  if (!isServer()) {
    throw new Error('protectSynced is server-only — a client cannot validate anything')
  }
  const definitions = components.map(asProtectedComponent)
  const componentIds: number[] = []
  for (const component of definitions) {
    componentIds.push(component.componentId)
    component.validateBeforeChange(entity, (change) => {
      if (isServerPeer(change.senderAddress, AUTH_SERVER_PEER_ID)) return true
      return validate({
        entity: change.entity,
        component,
        value: change.newValue,
        from: change.senderAddress
      })
    })
  }

  const entry: ProtectedEntry = { entity: Number(entity), componentIds }
  const { late } = ledger().record(entry.entity, componentIds)
  if (late.length > 0) {
    console.error(protectedLogLine('late', { entity: entry.entity, componentIds: late }))
  }
  publish(protectedLogLine('registered', entry))
}

/** Called by whoever emits the first heartbeat, once every validator is armed. */
export function sealProtectedRegistration(): void {
  ledger().seal()
}

interface ProtectedChangeInfo {
  entity: Entity
  newValue: unknown
  senderAddress: string
}

interface ProtectedComponent {
  componentId: number
  componentName: string
  has(entity: Entity): boolean
  create(entity: Entity): unknown
  validateBeforeChange(entity: Entity, cb: (change: ProtectedChangeInfo) => boolean): void
}

function asProtectedComponent(value: unknown): ProtectedComponent {
  if (!isProtectedComponent(value)) {
    throw new Error('protectedSync: `components` takes component definitions, not values')
  }
  return value
}

function isProtectedComponent(value: unknown): value is ProtectedComponent {
  return (
    typeof value === 'object' &&
    value !== null &&
    'componentId' in value &&
    typeof value.componentId === 'number' &&
    'componentName' in value &&
    typeof value.componentName === 'string' &&
    'has' in value &&
    typeof value.has === 'function' &&
    'create' in value &&
    typeof value.create === 'function' &&
    'validateBeforeChange' in value &&
    typeof value.validateBeforeChange === 'function'
  )
}

function ledger(): ProtectedLedger {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[SYNC_KEY]
  if (isLedger(current)) return current
  const created = new ProtectedLedger()
  globals[SYNC_KEY] = created
  return created
}

// Byte-identical copies of this file are still separate class identities, so
// probe the shared ledger by shape — instanceof would reject a sibling's.
function isLedger(value: unknown): value is ProtectedLedger {
  return (
    typeof value === 'object' &&
    value !== null &&
    'record' in value &&
    typeof value.record === 'function' &&
    'entries' in value &&
    typeof value.entries === 'function' &&
    'seal' in value &&
    typeof value.seal === 'function'
  )
}

let devRealm: boolean | null = null
const queued: string[] = []

// The dev gate. Two ways to be playing rather than published, and the editor is
// the second one: `dcl start` sets isPreview, while the editor's embedded
// explorer boots against a realm on this machine and reports isPreview false —
// which is exactly how the explorer itself tells the editor apart. Gating on
// isPreview alone made every editor Play look like a scene with no evidence at
// all. A public realm still opens nothing. If the query never answers, the
// queue is dropped rather than grown.
void getRealm({})
  .then((realm) => {
    devRealm = isDevRealm(realm.realmInfo)
    flushQueue()
  })
  .catch(() => {
    devRealm = false
    flushQueue()
  })

interface RealmInfoLike {
  baseUrl?: string
  realmName?: string
  isPreview?: boolean
}

const LOOPBACK_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '::1', '[::1]']

/**
 * Whether this session is a creator playing their own scene — preview, or a
 * realm served from this machine (the editor). Exported for the test that
 * pins the three realms apart; nothing else should need it.
 */
export function isDevRealm(info: RealmInfoLike | null | undefined): boolean {
  if (info === null || info === undefined) return false
  if (info.isPreview === true) return true
  return isLoopback(info.baseUrl) || isLoopback(info.realmName)
}

function isLoopback(url: string | undefined): boolean {
  if (typeof url !== 'string' || url === '') return false
  const afterScheme = url.includes('://') ? url.slice(url.indexOf('://') + 3) : url
  const authority = afterScheme.split(/[/?#]/)[0] ?? ''
  // an IPv6 literal keeps its brackets; everything else loses its port
  const closing = authority.startsWith('[') ? authority.indexOf(']') : -1
  const host = closing >= 0 ? authority.slice(0, closing + 1) : authority.split(':')[0]
  return LOOPBACK_HOSTS.includes((host ?? '').toLowerCase())
}

function publish(line: string): void {
  if (devRealm === true) {
    console.log(line)
    return
  }
  if (devRealm === null && queued.length < QUEUE_LIMIT) queued.push(line)
}

/**
 * One console line for the editor to parse off the Logs stream, on the same
 * dev gate the observed-authority lines ride — a published scene stays quiet.
 * Exported so a sibling module does not open a second getRealm query just to
 * answer the same question.
 */
export function previewLog(line: string): void {
  publish(line)
}

function flushQueue(): void {
  const lines = queued.splice(0)
  if (devRealm !== true) return
  for (const line of lines) console.log(line)
}
