// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import { engine } from '@dcl/sdk/ecs'
import { PhaseWatcher, advancePhase, type PhaseTuple } from './pure/phase'

// Tick helpers. Game logic runs on dt-accumulator systems, not wall-clock
// timers — and anything that must survive the server sleeping is an absolute
// deadline derived from the clock (see pure/countdown.ts), never a running
// setTimeout.
//
// A phase machine is the same idea one level up: the durable state is the tuple
// {phase, phaseStartMs} plus a cycle of phase durations, and "which phase are
// we in" is derived from the clock on both sides every frame (pure/phase.ts).
// onPhaseBoundary turns that derivation into hooks:
//
//   const stop = onPhaseBoundary(
//     () => ({ tuple: state.get(), durationsMs: [lobbyMs, waveMs, breakMs] }),
//     (phase, tuple) => enterPhase(phase, tuple)
//   )
//
// The hook fires once per boundary crossed — including the phase in progress
// when the script starts, because a client joining mid-round still has to enter
// it — and collapses a long sleep into the final phase instead of replaying
// hundreds of them.

export {
  remainingMs,
  isExpired,
  countdownRemainingMs,
  countdownWithMultiplier,
  settleExpired,
  periodId,
  dailyKey,
  weeklyKey,
  DAY_MS,
  WEEK_MS,
  type CountdownState
} from './pure/countdown'

export {
  advancePhase,
  phaseOf,
  phaseStartMsOf,
  phaseElapsedMs,
  phaseEndsAtMs,
  phaseRemainingMs,
  phaseIndexOf,
  durationOf,
  cycleMsOf,
  PhaseWatcher,
  type PhaseTuple,
  type PhaseAdvance
} from './pure/phase'

/** What onPhaseBoundary reads every frame: the durable tuple and the current duration cycle. */
export interface PhaseSource {
  tuple: PhaseTuple
  durationsMs: readonly number[]
}

/**
 * Run `tick` every `seconds` (dt-accumulated, so it pauses with the scene and
 * batches after hitches instead of drifting). Returns a stop function.
 */
export function interval(seconds: number, tick: (elapsed: number) => void, name?: string): () => void {
  let accum = 0
  const system = (dt: number): void => {
    accum += dt
    if (accum < seconds) return
    const elapsed = accum
    accum = 0
    tick(elapsed)
  }
  const systemName = name ?? `runtime-interval-${Math.floor(Math.random() * 1e9)}`
  engine.addSystem(system, undefined, systemName)
  return () => engine.removeSystem(systemName)
}

/**
 * Run `onEnter` for every phase boundary the clock has crossed. `read` returns
 * null while the tuple is not known yet (before the first server state lands),
 * which parks the watcher without firing. Returns a stop function.
 *
 * Catch-up phases (crossed while the server slept) are reported with the
 * CURRENT tuple: they are being settled, not lived.
 */
export function onPhaseBoundary(
  read: () => PhaseSource | null,
  onEnter: (phase: number, tuple: PhaseTuple) => void,
  name?: string
): () => void {
  const watcher = new PhaseWatcher()
  const system = (): void => {
    const source = read()
    if (source === null) return
    const current = advancePhase(source.tuple, source.durationsMs, Date.now())
    const advance = watcher.step(current.phase)
    if (advance === null) return
    for (const phase of advance.entered) onEnter(phase, current)
  }
  const systemName = name ?? `runtime-phase-${Math.floor(Math.random() * 1e9)}`
  engine.addSystem(system, undefined, systemName)
  return () => engine.removeSystem(systemName)
}
