// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import { isServer } from '@dcl/sdk/network'
import { Storage } from '@dcl/sdk/server'
import { ServerStore, claimStoreKey } from './pure/serverStore'

// Server-private state with a name. Anything a client must never see — the quiz
// answer, the loot roll, the next phase's seed before it is published — lives
// here instead of in a synced component, because a synced component reaches
// every peer by construction and no flag can change that.
//
// Every method THROWS on a client: reading server state from client code is a
// leak, so it is a loud crash in Play instead of a silent success. Call
// serverState() from a script's start() inside a server branch, never at module
// scope — the platform answers isServer() false until it has resolved.
//
//   const state = serverState<{ seed: number; phase: number }>({
//     key: 'round-loop', defaults: () => ({ seed: 0, phase: 0 }), persist: true
//   })
//   await state.restore()          // opt-in, only when persist is set
//   state.patch({ phase: 1 })      // or mutate state.get() directly
//   await state.flush()            // checkpoint: round end, player leave — never per tick
//                                  // answers 'clean' | 'stored' | 'refused'
//
// Persistence is scene-scoped Storage under `serverState:<key>`. A write that
// did not persist leaves the store dirty, so the next flush retries it, and
// restore() leaves it dirty too: the first flush after boot rewrites the
// canonical shape (Storage skips the write when the value is already stored).
//
// Keys are claimed globally, so two stores (or two prefabs carrying their own
// copy of this file) cannot silently share one store.

const STATE_KEY = '__dclServerState_v1'
const STORAGE_PREFIX = 'serverState:'

/** What a flush did: nothing to write, a write that landed, or a host that
 * refused it — the caller decides whether to retry, and a refusal that reads
 * the same as a no-op is a lost write nobody hears about. */
export type FlushOutcome = 'clean' | 'stored' | 'refused'

export interface ServerState<T> {
  get(): T
  patch(next: Partial<T>): void
  /** Opt-in Storage persistence; await it at boot before any serverStart work. */
  restore(): Promise<void>
  flush(): Promise<FlushOutcome>
}

export interface ServerStateOptions<T extends object> {
  /** Unique per store; include the entity when a prefab may be placed twice. */
  key: string
  defaults: () => T
  persist?: boolean
}

export function serverState<T extends object>(options: ServerStateOptions<T>): ServerState<T> {
  assertServer(`serverState('${options.key}')`)
  claimStoreKey(claimedKeys(), options.key)

  const store = new ServerStore<T>({ key: options.key, defaults: options.defaults })
  const persist = options.persist === true
  const storageKey = `${STORAGE_PREFIX}${options.key}`

  return {
    get(): T {
      assertServer(`serverState('${options.key}').get`)
      return store.get()
    },
    patch(next: Partial<T>): void {
      assertServer(`serverState('${options.key}').patch`)
      store.patch(next)
    },
    async restore(): Promise<void> {
      assertServer(`serverState('${options.key}').restore`)
      if (!persist) return
      const raw = await Storage.get<unknown>(storageKey)
      if (raw === null) return
      store.adopt(raw)
    },
    async flush(): Promise<FlushOutcome> {
      assertServer(`serverState('${options.key}').flush`)
      if (!persist || !store.needsFlush()) return 'clean'
      const { value, encoded } = store.snapshot()
      if (!(await Storage.set(storageKey, value))) return 'refused'
      store.markPersisted(encoded)
      return 'stored'
    }
  }
}

function assertServer(what: string): void {
  if (!isServer()) {
    throw new Error(`${what} is server-only — server state must never be reachable from a client`)
  }
}

interface KeyRegistry {
  keys: Set<string>
}

// Anchored on globalThis, not module scope: every prefab bundles its own copy
// of this file, so module scope would give each prefab its own key namespace
// and the collision guard would never fire (same rule as zoneBus).
function claimedKeys(): Set<string> {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[STATE_KEY]
  if (isKeyRegistry(current)) return current.keys
  const created: KeyRegistry = { keys: new Set<string>() }
  globals[STATE_KEY] = created
  return created.keys
}

function isKeyRegistry(value: unknown): value is KeyRegistry {
  return typeof value === 'object' && value !== null && 'keys' in value && value.keys instanceof Set
}
