// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import { engine, Schemas, type Entity } from '@dcl/sdk/ecs'
import { isServer, syncEntity } from '@dcl/sdk/network'
import { AUTH_SERVER_PEER_ID } from '@dcl/sdk/network/message-bus-sync'
import { LivenessTracker } from './pure/liveness'
import { sealProtectedRegistration } from './protectedSync'

// Server heartbeat + client liveness. The server pulses a counter into a
// synced, server-protected component every ~2s; clients judge life by when they
// OBSERVED it change (see pure/liveness.ts), never by the value itself — a
// stale CRDT snapshot from a previous server run carries one. Every prefab that
// talks to the server gates its UX on serverLifeState() instead of trusting
// isStateSyncronized() (room transport ≠ server awake — the cold-start wedge
// every shipped game had).
//
// THE STATE LADDER (one enum, rendered verbatim by every surface — no HUD,
// panel or script invents its own vocabulary):
//
//   waking      no heartbeat yet, still inside the cold-start window. The
//               player-facing default: "Waking the game server… Xs".
//   running     a beat landed within 3 pulses.
//   degraded    beats stopped for 3× the pulse interval but not long enough to
//               call it sleep — a hitch, a reconnect, or a server going down.
//               Gameplay keeps rendering; anything the server decides should
//               stop claiming to be current.
//   asleep      silent past the sleep window after having been alive. The
//               Multiplayer Server sleeps when the scene empties; the next
//               visitor's traffic wakes it and the state returns to running.
//   unreachable never reached at all within the cold-start window. Something is
//               wrong with the deployment, not with this session.
//
// READINESS GATING. The heartbeat is the signal clients use to start trusting
// the server, so it must not fire before the server can be trusted: no beat is
// emitted until markServerReady() is called, which every server branch calls
// once its validators are armed and its synced singletons are claimed. That
// closes the window where a racing client's writes would pass unvalidated.
// A server that never calls it never beats — the module says so in the logs.
//
// Readiness is an AND across PARTICIPANTS, not a single flag. Two kit prefabs in
// one scene each call startServerLife(id) and each answer with markServerReady(id);
// the first beat waits for the last of them, so one prefab that arms synchronously
// cannot announce a server whose neighbour is still rehydrating from Storage.
// sealProtectedRegistration() rides the same gate, on the first server TICK at
// which nothing is pending — never inside markServerReady(), which would seal the
// ledger before a prefab whose start() runs second has armed anything.
//
// Cross-copy: every prefab carries its own copy of this file, so the whole driver
// — role, ladder, pending set, beat count — lives on globalThis.__dclServerLife_v1
// and is probed by shape. Two module-scope copies would be two heartbeat loops
// writing one entity, and a readiness gate only as strong as the earliest caller.

const DRIVER_KEY = '__dclServerLife_v1'
const DEFAULT_PARTICIPANT = 'server'
const PULSE_S = 2
// Three missed pulses is the degraded threshold, and the same number the
// liveness tracker uses to stop calling the server alive.
const DEGRADED_AFTER_MS = PULSE_S * 3 * 1000
const ASLEEP_AFTER_MS = 30_000
const WAKE_TIMEOUT_MS = 20_000
const READY_WARN_AFTER_MS = 5_000

export type ServerLifeState = 'running' | 'waking' | 'degraded' | 'asleep' | 'unreachable'

export interface ServerLifeThresholds {
  degradedAfterMs: number
  asleepAfterMs: number
  wakeTimeoutMs: number
}

export const SERVER_LIFE_THRESHOLDS: ServerLifeThresholds = {
  degradedAfterMs: DEGRADED_AFTER_MS,
  asleepAfterMs: ASLEEP_AFTER_MS,
  wakeTimeoutMs: WAKE_TIMEOUT_MS
}

/**
 * The client half of the ladder, as pure state: observe the visible heartbeat
 * value, read a state. Exported so a HUD can render the same ladder off its own
 * samples and so it is unit-testable without the engine.
 */
export class ServerLifeLadder {
  private tracker: LivenessTracker
  private lastValue: number | null = null
  private lastBeatAtMs: number | null = null
  private startedAtMs: number | null = null

  constructor(private thresholds: ServerLifeThresholds = SERVER_LIFE_THRESHOLDS) {
    this.tracker = new LivenessTracker(thresholds.degradedAfterMs)
  }

  /** Starts the cold-start window. Called once, when the module starts watching. */
  start(nowMs: number): void {
    if (this.startedAtMs === null) this.startedAtMs = nowMs
  }

  /** Feed the currently visible heartbeat value (null when absent). True when a beat landed. */
  observe(value: number | null, nowMs: number): boolean {
    const changed = value !== null && value !== this.lastValue
    this.tracker.observe(value, nowMs)
    if (!changed) return false
    this.lastValue = value
    this.lastBeatAtMs = nowMs
    return true
  }

  state(nowMs: number): ServerLifeState {
    if (this.lastBeatAtMs === null) {
      return this.ageMs(nowMs) > this.thresholds.wakeTimeoutMs ? 'unreachable' : 'waking'
    }
    switch (this.tracker.state(nowMs)) {
      case 'alive':
        return 'running'
      default:
        return this.ageMs(nowMs) > this.thresholds.asleepAfterMs ? 'asleep' : 'degraded'
    }
  }

  /** Since the last beat, or since the watch started when none ever landed. */
  ageMs(nowMs: number): number {
    const since = this.lastBeatAtMs ?? this.startedAtMs
    return since === null ? 0 : Math.max(0, nowMs - since)
  }

  everAlive(): boolean {
    return this.tracker.everAlive()
  }
}

// Idempotent def: every prefab bundles its own copy of this file.
function defineHeartbeat() {
  return engine.defineComponent('runtime::Heartbeat', { beat: Schemas.Int64 })
}
const Heartbeat =
  (engine.getComponentOrNull('runtime::Heartbeat') as ReturnType<typeof defineHeartbeat> | null) ?? defineHeartbeat()

interface ServerLifeDriver {
  role: 'server' | 'client' | null
  /** participants that called startServerLife() and have not answered yet */
  pending: Set<string>
  sealed: boolean
  readyWarned: boolean
  beatsSent: number
  serverStartedAtMs: number
  ladder: ServerLifeLadder
}

// Byte-identical copies of this file are still separate module instances, so the
// shared driver is probed by shape — instanceof would reject a sibling's.
function isDriver(value: unknown): value is ServerLifeDriver {
  return (
    typeof value === 'object' &&
    value !== null &&
    'pending' in value &&
    value.pending instanceof Set &&
    'ladder' in value &&
    typeof value.ladder === 'object' &&
    value.ladder !== null
  )
}

function driver(): ServerLifeDriver {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[DRIVER_KEY]
  if (isDriver(current)) return current
  const created: ServerLifeDriver = {
    role: null,
    pending: new Set<string>(),
    sealed: false,
    readyWarned: false,
    beatsSent: 0,
    serverStartedAtMs: 0,
    ladder: new ServerLifeLadder()
  }
  globals[DRIVER_KEY] = created
  return created
}

/**
 * Start watching (client) or driving (server) the heartbeat. `id` names this
 * participant: the server's first beat waits until every id that started has
 * answered with markServerReady(id). One id per PREFAB, not per instance — a
 * second placed copy of the same prefab is the same participant.
 */
export function startServerLife(id: string = DEFAULT_PARTICIPANT): void {
  const live = driver()
  const server = live.role === null ? isServer() : live.role === 'server'
  if (server) live.pending.add(id)
  if (live.role !== null) return
  live.role = server ? 'server' : 'client'
  live.ladder.start(Date.now())
  if (live.role === 'server') startServer()
  else startClient()
}

/**
 * Answers for one participant. Call once, from the server branch, AFTER every
 * validateBeforeChange is registered and every synced singleton is claimed.
 * No-op on clients, idempotent. `id` must match this participant's
 * startServerLife(id).
 */
export function markServerReady(id: string = DEFAULT_PARTICIPANT): void {
  driver().pending.delete(id)
}

function isReady(live: ServerLifeDriver): boolean {
  return live.pending.size === 0
}

/** waking → running, and the degraded/asleep/unreachable failure ladder. */
export function serverLifeState(): ServerLifeState {
  const live = driver()
  if (live.role === 'server') return isReady(live) ? 'running' : 'waking'
  return live.ladder.state(Date.now())
}

function heartbeatEntity(): Entity | null {
  for (const [entity] of engine.getEntitiesWith(Heartbeat)) return entity
  return null
}

function startServer(): void {
  Heartbeat.validateBeforeChange(({ senderAddress }) => senderAddress.toLowerCase() === AUTH_SERVER_PEER_ID)
  driver().serverStartedAtMs = Date.now()
  let accum = 0
  engine.addSystem(
    (dt: number) => {
      const live = driver()
      if (!isReady(live)) {
        warnWhenReadyIsLate(live)
        return
      }
      // The seal waits for a TICK, not for the last markServerReady(): every
      // script's start() runs before the first system, so this is the first
      // moment "every participant has registered" is knowable. Sealing inside
      // markServerReady() instead reported the prefab whose start() ran second
      // as a late registration, purely because of script order.
      if (!live.sealed) {
        live.sealed = true
        sealProtectedRegistration()
      }
      accum += dt
      // The first beat goes out on the tick readiness lands, not a pulse later.
      if (live.beatsSent > 0 && accum < PULSE_S) return
      accum = 0
      pulse(live)
    },
    undefined,
    'runtime-server-life'
  )
}

function pulse(live: ServerLifeDriver): void {
  const existing = heartbeatEntity()
  if (existing === null) {
    const entity = engine.addEntity()
    Heartbeat.create(entity, { beat: Date.now() })
    syncEntity(entity, [Heartbeat.componentId])
  } else {
    Heartbeat.getMutable(existing).beat = Date.now()
  }
  live.beatsSent++
}

function warnWhenReadyIsLate(live: ServerLifeDriver): void {
  if (live.readyWarned || Date.now() - live.serverStartedAtMs < READY_WARN_AFTER_MS) return
  live.readyWarned = true
  console.log(
    `[SERVER] serverLife: heartbeat withheld — markServerReady() has not been called by ${[...live.pending].join(', ')}, so every client stays in "waking". Call it once your validators are armed.`
  )
}

function startClient(): void {
  engine.addSystem(
    () => {
      const live = driver()
      const entity = heartbeatEntity()
      const value = entity !== null ? Number(Heartbeat.get(entity).beat) : null
      live.ladder.observe(value, Date.now())
    },
    undefined,
    'runtime-server-life'
  )
}
