// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import { engine, Schemas } from '@dcl/sdk/ecs'
import { isServer, registerMessages } from '@dcl/sdk/network'
import { ntpSample, combineSamples, type NtpSample } from './pure/time-math'

// NTP-style server clock sync. Server answers timestamp probes; clients sample
// a few round-trips, drop outliers, and keep a clock offset. All shared
// deadlines are expressed in *server* time and derived locally — see
// pure/countdown.ts.
//
//   initTimeSync()                 // both sides, once, from main()
//   const now = getServerTime()    // server-clock "now" on either side

const room = registerMessages({
  'runtime.timeSync': Schemas.Map({ id: Schemas.String }),
  'runtime.timeSyncResponse': Schemas.Map({
    id: Schemas.String,
    t2: Schemas.Int64,
    t3: Schemas.Int64
  })
})

const SAMPLES_NEEDED = 5
const SAMPLE_INTERVAL_S = 0.15
const RESYNC_INTERVAL_S = 60
const RESPONSE_TIMEOUT_S = 2

let initialized = false
let ready = false
let offsetMs = 0

export function initTimeSync(): void {
  if (initialized) return
  initialized = true
  if (isServer()) {
    let logged = false
    room.onMessage('runtime.timeSync', (data, context) => {
      if (!context) return
      if (!logged) {
        logged = true
        console.log('[timeSync] server: first sync request from', context.from)
      }
      const now = Date.now()
      room.send('runtime.timeSyncResponse', { id: data.id, t2: now, t3: now }, { to: [context.from] })
    })
    ready = true
    console.log('[timeSync] server responder ready')
    return
  }
  console.log('[timeSync] client sync starting')
  initClient()
}

/** Server-clock now. On the server this is Date.now(); on a client it is Date.now() + offset. */
export function getServerTime(): number {
  return Date.now() + offsetMs
}

export function isTimeSyncReady(): boolean {
  return ready
}

function initClient(): void {
  const sessionId = Math.floor(Math.random() * 0xffffffff).toString(36)
  let counter = 0
  let samples: NtpSample[] = []
  let syncing = false
  let pendingId: string | null = null
  let pendingT1 = 0
  let sampleTimer = 0
  let resyncTimer = 0

  room.onMessage('runtime.timeSyncResponse', (data) => {
    if (data.id !== pendingId) return
    pendingId = null
    // Int64 fields can arrive as BigInt depending on the SDK build — mixing
    // BigInt into number arithmetic throws and silently kills the handler
    samples.push(ntpSample(pendingT1, Number(data.t2), Number(data.t3), Date.now()))
    if (samples.length >= SAMPLES_NEEDED) {
      offsetMs = combineSamples(samples)
      samples = []
      syncing = false
      ready = true
      resyncTimer = 0
      console.log('[timeSync] client synced, offset', Math.round(offsetMs), 'ms')
    }
  })

  engine.addSystem((dt: number) => {
    // no connectivity gate: readiness signals are unreliable across SDK builds
    // and after in-place scene reloads — send-and-retry is the handshake
    if (!ready && !syncing) {
      syncing = true
      samples = []
      sampleTimer = SAMPLE_INTERVAL_S
      pendingId = null
      return
    }

    if (syncing) {
      sampleTimer += dt
      if (pendingId !== null && sampleTimer > RESPONSE_TIMEOUT_S) {
        pendingId = null // lost response — resend
        sampleTimer = 0
        console.log('[timeSync] client: no response, resending')
      }
      if (pendingId === null && sampleTimer >= SAMPLE_INTERVAL_S) {
        sampleTimer = 0
        pendingId = `${sessionId}:${++counter}`
        pendingT1 = Date.now()
        try {
          room.send('runtime.timeSync', { id: pendingId })
        } catch {
          pendingId = null // transport not up yet — next tick retries
        }
      }
      return
    }

    resyncTimer += dt
    if (resyncTimer >= RESYNC_INTERVAL_S) {
      resyncTimer = 0
      syncing = true
    }
  }, undefined, 'runtime-time-sync')
}
