// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import {
  PlayerIdentityData,
  Schemas,
  engine,
  type Entity,
  type LastWriteWinElementSetComponentDefinition
} from '@dcl/sdk/ecs'
import { ZoneRegistry, type ZoneEventKind, type ZoneListenKind } from './pure/zoneRegistry'

// Cross-script zone composition. A consumer references a zone BY NAME — the name
// the creator typed in the hierarchy — so the direction of reference is always
// consumer → zone and a script pasted into another scene keeps working.
//
// Occupancy is the primary API. isInZone() cannot flicker the way an event
// stream can, and a door asking "is anyone in the Front Hall" does not close
// when the second of two people leaves.
//
//   if (isInZone('Front Hall')) this.open()            // consumer
//   publishZone(name, this.entity, () => members)      // producer: TriggerZone only
//
// The registry is anchored on globalThis rather than in module scope because
// every prefab bundles its OWN copy of this file (the ui-owner.ts convention):
// two module instances would be two disconnected buses.

const BUS_KEY = '__dclZoneBus_v1'

export interface ZoneEvent {
  zone: string
  kind: ZoneEventKind
  /** The avatar that moved — never the area. */
  entity: Entity
  address: string
  /** True when the avatar is this viewer. */
  local: boolean
  zoneEntity: Entity
}

export type { ZoneEventKind, ZoneListenKind }

/** True when THIS viewer is inside a zone with that name. */
export function isInZone(zone: string): boolean {
  return registry().contains(zone, engine.PlayerEntity)
}

/** Every avatar currently inside, deduped across areas that share the name. */
export function playersInZone(zone: string): Entity[] {
  return registry().occupants(zone)
}

/** Published zone names, in the creator's spelling. */
export function zoneNames(): string[] {
  return registry().names()
}

/**
 * The zone name of the entity this script is attached to — its Name, since that
 * IS the zone id. Lets a reaction script sitting ON a zone leave its `zone` param
 * blank: nothing to type, and renaming the zone can't orphan it. Returns '' for an
 * entity with no Name (a reaction attached elsewhere must name its zone).
 */
export function zoneOf(entity: Entity): string {
  return nameComponent().getOrNull(entity)?.value ?? ''
}

type NameValue = { value: string }
type NameComponent = LastWriteWinElementSetComponentDefinition<NameValue>

// A sibling copy of this module may already have defined it (see isRegistry).
function nameComponent(): NameComponent {
  const existing = engine.getComponentOrNull('core-schema::Name')
  if (existing !== null) return existing as NameComponent
  return engine.defineComponent('core-schema::Name', { value: Schemas.String })
}

/** Edges, derived from the occupancy set. Late subscribers get current occupancy replayed as enters. */
export function onZone(zone: string, kind: ZoneListenKind, fn: (event: ZoneEvent) => void): () => void {
  return registry().subscribe(zone, kind, (eventKind, who, zoneEntity) => fn(describe(zone, eventKind, who, zoneEntity)))
}

/**
 * Producer side, called only by the trigger-zone prefab. There is deliberately no
 * unpublish: the script runtime has no destroy hook, so the only caller would be a
 * consumer, and unpublishing a zone whose area still fires breaks it silently.
 * ZoneRegistry.unpublish is where that lands the day a destroy hook exists.
 */
export function publishZone(zone: string, zoneEntity: Entity, occupants: () => Entity[]): void {
  registry().publish(zone, zoneEntity, occupants)
}

export function emitZone(zone: string, kind: ZoneEventKind, who: Entity, zoneEntity: Entity): void {
  registry().emit(zone, kind, who, zoneEntity)
}

function describe(zone: string, kind: ZoneEventKind, who: Entity, zoneEntity: Entity): ZoneEvent {
  return {
    zone: registry().displayName(zone),
    kind,
    entity: who,
    address: PlayerIdentityData.getOrNull(who)?.address ?? '',
    local: who === engine.PlayerEntity,
    zoneEntity
  }
}

function registry(): ZoneRegistry<Entity> {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[BUS_KEY]
  if (isRegistry(current)) return current
  const created = new ZoneRegistry<Entity>()
  globals[BUS_KEY] = created
  return created
}

// Two prefabs bundle two copies of this file, so the two ZoneRegistry classes are
// different objects and `instanceof` would reject the shared bus. Shape is the
// only identity that survives; the copies are byte-identical by test.
function isRegistry(value: unknown): value is ZoneRegistry<Entity> {
  return (
    typeof value === 'object' &&
    value !== null &&
    'emit' in value &&
    typeof value.emit === 'function' &&
    'subscribe' in value &&
    typeof value.subscribe === 'function'
  )
}
